### ISSUE TITLE
OBS on Linux segfaults when starting/stopping playback from various sources, seems to be related to pipewire/jack

### ISSUE THREAD

**Issue by Teascade** [obsproject/obs-studio#11156]
### Operating System Info

Other

### Other OS

ArchLinux (6.10.4-arch2-1)

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.2.1-1 (latest from ArchLinux official repos)

### OBS Studio Log URL

https://obsproject.com/logs/xydLjSF8jOVzXOML

### OBS Studio Crash Log URL

https://obsproject.com/logs/xydLjSF8jOVzXOML

### Expected Behavior

Sometime earlier this year, obs was working as intended, by which I mean that obs never segfaulted regardless of how I started or stopped playbacks during the program running (YouTube/Spotify/Netflix/etc.).

### Current Behavior

OBS segfaults either when starting playback or stopping it. It seems to be random which causes it, and sometimes it seems to be source-specific. Unclear.

### Steps to Reproduce

1. Launch OBS (in safe mode or otherwise)
2. Start (and possibly stop) playback from YouTube/Netflix/Spotify/etc., videogames don't seem to be affected, only web-applications so far that I can tell.

### Anything else we should know?

Full GDB logs and `backtrace -full` after segmentation fault, which causes me to believe the issue is related to pipewire/pipewire-jack.

Other related versions are:
```
pipewire-alsa 1:1.2.2-1
pipewire-jack 1:1.2.2-1
pipewire-pulse 1:1.2.2-1
```

The GDB logs in their entirety:
```
Starting program: /usr/bin/obs --safe-mode
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe1c006c0 (LWP 516163)]
[New Thread 0x7fffe12006c0 (LWP 516164)]
[New Thread 0x7fffdbe006c0 (LWP 516165)]
[New Thread 0x7fffdb4006c0 (LWP 516166)]
[New Thread 0x7fffdaa006c0 (LWP 516167)]
[New Thread 0x7fffda0006c0 (LWP 516168)]
debug: Found portal inhibitor
debug: Attempted path: /usr/bin/../share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/bin/../share/obs/obs-studio/locale.ini
debug: Attempted path: /usr/bin/../share/obs/obs-studio/themes
debug: Attempted path: /usr/bin/../share/obs/obs-studio/themes/
warning: Get on org.freedesktop.portal.Settings returned an invalid reply
warning: [Safe Mode] Unclean shutdown detected!
info: Command Line Arguments: --safe-mode
info: Platform: Wayland
info: CPU Name: AMD Ryzen 9 5900X 12-Core Processor
info: CPU Speed: 2200.000MHz
info: Physical Cores: 12, Logical Cores: 24
info: Physical Memory: 32017MB Total, 11675MB Free
info: Kernel Version: Linux 6.10.4-arch2-1
info: Distribution: "Arch Linux" Unknown
info: Desktop Environment: wlroots
info: Session Type: wayland
[New Thread 0x7fffd96006c0 (LWP 516169)]
[New Thread 0x7fffd8c006c0 (LWP 516170)]
info: Qt Version: 6.7.2 (runtime), 6.7.2 (compiled)
info: Portable mode: false
warning: Safe Mode enabled.
[New Thread 0x7fffd3e006c0 (LWP 516171)]
[New Thread 0x7fffd34006c0 (LWP 516172)]
[New Thread 0x7fffd2a006c0 (LWP 516173)]
[New Thread 0x7fffd20006c0 (LWP 516174)]
info: OBS 30.2.1-1 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
	max buffering:   960 milliseconds
	buffering type:  dynamically increasing
[New Thread 0x7fffd16006c0 (LWP 516175)]
info: ---------------------------------
info: Initializing OpenGL...
info: Using EGL/Wayland
Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
[New Thread 0x7fffd0c006c0 (LWP 516320)]
[New Thread 0x7fffc5a006c0 (LWP 516321)]
[New Thread 0x7fffc50006c0 (LWP 516322)]
[New Thread 0x7fffbbe006c0 (LWP 516323)]
[New Thread 0x7fffbb4006c0 (LWP 516324)]
[New Thread 0x7fffbaa006c0 (LWP 516325)]
info: Initialized EGL 1.5
[New Thread 0x7fffba0006c0 (LWP 516326)]
[New Thread 0x7fffb96006c0 (LWP 516327)]
[New Thread 0x7fffb8c006c0 (LWP 516328)]
info: Loading up OpenGL on adapter AMD AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 18.1.8, DRM 3.57, 6.10.4-arch2-1)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 24.1.5-arch1.2, shading language 4.60
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1920x1080
	downscale filter:  Bilinear
	fps:               60/1
	format:            NV12
	YUV mode:          Rec. 709/Partial
[New Thread 0x7fffafe006c0 (LWP 516329)]
info: NV12 texture support enabled
info: P010 texture support not available
[New Thread 0x7fffadc006c0 (LWP 516330)]
info: Audio monitoring device:
	name: Monitor of Ti USB Audio  Analog Stereo
	id: alsa_output.usb-Texas_Instruments_Ti_USB_Audio-00.analog-stereo.monitor
info: ---------------------------------
[Detaching after fork from child process 516331]
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
[Detaching after fork from child process 516332]
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
[Detaching after fork from child process 516333]
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
[Detaching after fork from child process 516334]
warning: Skipping module 'frontend-tools', not on safe list
[Detaching after fork from child process 516335]
[Detaching after fork from child process 516336]
[Detaching after fork from child process 516337]
[Detaching after fork from child process 516338]
[Detaching after fork from child process 516339]
info: [pipewire] Available capture sources:
info: [pipewire]     - Monitor source
[Detaching after fork from child process 516346]
[Detaching after fork from child process 516347]
[Detaching after vfork from child process 516348]
warning: v4l2loopback not installed, virtual camera not registered
[Detaching after fork from child process 516350]
[New Thread 0x7fffa20006c0 (LWP 516356)]
[New Thread 0x7fffa16006c0 (LWP 516357)]
[New Thread 0x7fffa0c006c0 (LWP 516358)]
[New Thread 0x7fff97e006c0 (LWP 516359)]
[New Thread 0x7fff974006c0 (LWP 516360)]
[New Thread 0x7fff96a006c0 (LWP 516361)]
[New Thread 0x7fff960006c0 (LWP 516362)]
[New Thread 0x7fff956006c0 (LWP 516363)]
info: VAAPI: API version 1.22
[Thread 0x7fff96a006c0 (LWP 516361) exited]
[Thread 0x7fff956006c0 (LWP 516363) exited]
[Thread 0x7fff960006c0 (LWP 516362) exited]
[Thread 0x7fffa0c006c0 (LWP 516358) exited]
[Thread 0x7fffa16006c0 (LWP 516357) exited]
[Thread 0x7fff97e006c0 (LWP 516359) exited]
[Thread 0x7fff974006c0 (LWP 516360) exited]
[Thread 0x7fffa20006c0 (LWP 516356) exited]
info: FFmpeg VAAPI H264 encoding supported
[New Thread 0x7fffa20006c0 (LWP 516364)]
[New Thread 0x7fff974006c0 (LWP 516365)]
[New Thread 0x7fff97e006c0 (LWP 516366)]
[New Thread 0x7fffa0c006c0 (LWP 516367)]
[New Thread 0x7fffa16006c0 (LWP 516368)]
[New Thread 0x7fff96a006c0 (LWP 516369)]
[New Thread 0x7fff960006c0 (LWP 516370)]
[New Thread 0x7fff956006c0 (LWP 516371)]
[Thread 0x7fff96a006c0 (LWP 516369) exited]
[Thread 0x7fff960006c0 (LWP 516370) exited]
[Thread 0x7fff956006c0 (LWP 516371) exited]
[Thread 0x7fff97e006c0 (LWP 516366) exited]
[Thread 0x7fff974006c0 (LWP 516365) exited]
[Thread 0x7fffa0c006c0 (LWP 516367) exited]
[Thread 0x7fffa16006c0 (LWP 516368) exited]
[Thread 0x7fffa20006c0 (LWP 516364) exited]
info: FFmpeg VAAPI AV1 encoding supported
[New Thread 0x7fffa20006c0 (LWP 516372)]
[New Thread 0x7fffa16006c0 (LWP 516373)]
[New Thread 0x7fffa0c006c0 (LWP 516374)]
[New Thread 0x7fff97e006c0 (LWP 516375)]
[New Thread 0x7fff974006c0 (LWP 516376)]
[New Thread 0x7fff96a006c0 (LWP 516377)]
[New Thread 0x7fff960006c0 (LWP 516378)]
[New Thread 0x7fff956006c0 (LWP 516379)]
[Thread 0x7fff96a006c0 (LWP 516377) exited]
[Thread 0x7fff956006c0 (LWP 516379) exited]
[Thread 0x7fff960006c0 (LWP 516378) exited]
[Thread 0x7fffa0c006c0 (LWP 516374) exited]
[Thread 0x7fffa16006c0 (LWP 516373) exited]
[Thread 0x7fff97e006c0 (LWP 516375) exited]
[Thread 0x7fff974006c0 (LWP 516376) exited]
[Thread 0x7fffa20006c0 (LWP 516372) exited]
info: FFmpeg VAAPI HEVC encoding supported
[Detaching after fork from child process 516380]
[Detaching after fork from child process 516381]
[Detaching after fork from child process 516382]
[Detaching after fork from child process 516383]
[New Thread 0x7fffa20006c0 (LWP 516384)]
[New Thread 0x7fff974006c0 (LWP 516385)]
[New Thread 0x7fff97e006c0 (LWP 516386)]
[New Thread 0x7fffa0c006c0 (LWP 516387)]
[New Thread 0x7fffa16006c0 (LWP 516388)]
[New Thread 0x7fff96a006c0 (LWP 516389)]
[New Thread 0x7fff960006c0 (LWP 516390)]
[New Thread 0x7fff956006c0 (LWP 516391)]
[Thread 0x7fff96a006c0 (LWP 516389) exited]
[Thread 0x7fff956006c0 (LWP 516391) exited]
[Thread 0x7fff960006c0 (LWP 516390) exited]
[Thread 0x7fff974006c0 (LWP 516385) exited]
[Thread 0x7fff97e006c0 (LWP 516386) exited]
[Thread 0x7fffa0c006c0 (LWP 516387) exited]
[Thread 0x7fffa16006c0 (LWP 516388) exited]
[Thread 0x7fffa20006c0 (LWP 516384) exited]
[New Thread 0x7fffa20006c0 (LWP 516392)]
[New Thread 0x7fffa16006c0 (LWP 516393)]
[New Thread 0x7fffa0c006c0 (LWP 516394)]
[New Thread 0x7fff97e006c0 (LWP 516395)]
[New Thread 0x7fff974006c0 (LWP 516396)]
[New Thread 0x7fff96a006c0 (LWP 516397)]
[New Thread 0x7fff960006c0 (LWP 516398)]
[New Thread 0x7fff956006c0 (LWP 516399)]
[New Thread 0x7fff94c006c0 (LWP 516400)]
[New Thread 0x7fff87c006c0 (LWP 516401)]
[Thread 0x7fff96a006c0 (LWP 516397) exited]
[Thread 0x7fff87c006c0 (LWP 516401) exited]
[Thread 0x7fff94c006c0 (LWP 516400) exited]
[Thread 0x7fff956006c0 (LWP 516399) exited]
[Thread 0x7fff960006c0 (LWP 516398) exited]
[Thread 0x7fffa0c006c0 (LWP 516394) exited]
[Thread 0x7fffa16006c0 (LWP 516393) exited]
[Thread 0x7fff97e006c0 (LWP 516395) exited]
[Thread 0x7fff974006c0 (LWP 516396) exited]
[Thread 0x7fffa20006c0 (LWP 516392) exited]
[Detaching after fork from child process 516402]
[Detaching after fork from child process 516403]
[Detaching after fork from child process 516404]
[Detaching after fork from child process 516405]
[Detaching after fork from child process 516406]
[New Thread 0x7fffa20006c0 (LWP 516407)]
[New Thread 0x7fff974006c0 (LWP 516408)]
[Detaching after fork from child process 516409]
[Thread 0x7fff974006c0 (LWP 516408) exited]
info: ---------------------------------
info:   Loaded Modules:
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-webrtc.so
info:     obs-vst.so
info:     obs-transitions.so
info:     obs-qsv11.so
info:     obs-outputs.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-pipewire.so
info:     linux-jack.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     decklink-output-ui.so
info:     decklink-captions.so
info: ---------------------------------
info: ---------------------------------
info: Available Encoders:
info:   Video Encoders:
info: 	- ffmpeg_svt_av1 (SVT-AV1)
info: 	- ffmpeg_aom_av1 (AOM AV1)
info: 	- ffmpeg_vaapi_tex (FFmpeg VAAPI H.264)
info: 	- av1_ffmpeg_vaapi_tex (FFmpeg VAAPI AV1)
info: 	- hevc_ffmpeg_vaapi_tex (FFmpeg VAAPI HEVC)
info: 	- obs_x264 (x264)
info:   Audio Encoders:
info: 	- ffmpeg_aac (FFmpeg AAC)
info: 	- ffmpeg_opus (FFmpeg Opus)
info: 	- ffmpeg_pcm_s16le (FFmpeg PCM (16-bit))
info: 	- ffmpeg_pcm_s24le (FFmpeg PCM (24-bit))
info: 	- ffmpeg_pcm_f32le (FFmpeg PCM (32-bit float))
info: 	- ffmpeg_alac (FFmpeg ALAC (24-bit))
info: 	- ffmpeg_flac (FFmpeg FLAC (16-bit))
info: 	- libfdk_aac (libfdk AAC)
info: ==== Startup complete ===============================================
info: All scene data cleared
info: ------------------------------------------------
[New Thread 0x7fff974006c0 (LWP 516410)]
info: pulse-input: Server name: 'PulseAudio (on PipeWire 1.2.2) 15.0.0'
info: pulse-input: Audio format: float32le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'bluez_output.00_0A_45_25_32_D8.1.monitor' (default)
info: [Loaded global audio device]: 'Desktop Audio'
error: Source ID 'xcomposite_input' not found
error: Failed to create source 'Window Capture (Xcomposite) 2'!
[New Thread 0x7fff97e006c0 (LWP 516411)]
[New Thread 0x7fffa0c006c0 (LWP 516412)]
[Thread 0x7fffa0c006c0 (LWP 516412) exited]
[New Thread 0x7fffa0c006c0 (LWP 516413)]
[New Thread 0x7fffa16006c0 (LWP 516415)]
[New Thread 0x7fff96a006c0 (LWP 516416)]
error: Source ID 'xcomposite_input' not found
error: Failed to create source 'WOLT'!
[swscaler @ 0x555557138900] deprecated pixel format used, make sure you did set range correctly
error: Source ID 'xcomposite_input' not found
error: Failed to create source 'RuneLite'!
error: Source ID 'xcomposite_input' not found
error: Failed to create source 'EldenRing'!
error: Source ID 'xcomposite_input' not found
error: Failed to create source 'ds1'!
error: Source ID 'xcomposite_input' not found
error: Failed to create source 'ds2'!
[swscaler @ 0x555557357240] deprecated pixel format used, make sure you did set range correctly
info: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: musicinput)

[New Thread 0x7fff95c006c0 (LWP 516418)]
[New Thread 0x7fff952006c0 (LWP 516419)]
[Thread 0x7fff952006c0 (LWP 516419) exited]
[New Thread 0x7fff952006c0 (LWP 516420)]
[New Thread 0x7fff87c006c0 (LWP 516421)]
[New Thread 0x7fff872006c0 (LWP 516422)]
[New Thread 0x7fff868006c0 (LWP 516423)]
[New Thread 0x7fff85e006c0 (LWP 516424)]
[Thread 0x7fff85e006c0 (LWP 516424) exited]
[New Thread 0x7fff85e006c0 (LWP 516425)]
[New Thread 0x7fff854006c0 (LWP 516426)]
[New Thread 0x7fff84a006c0 (LWP 516428)]
[New Thread 0x7fff73e006c0 (LWP 516429)]
[New Thread 0x7fff734006c0 (LWP 516430)]
[Thread 0x7fff734006c0 (LWP 516430) exited]
[New Thread 0x7fff734006c0 (LWP 516431)]
[New Thread 0x7fff72a006c0 (LWP 516437)]
[New Thread 0x7fff720006c0 (LWP 516438)]
error: Source ID 'xcomposite_input' not found
error: Failed to create source 'Window Capture (Xcomposite)'!
error: Source ID 'xshm_input' not found
error: Failed to create source 'Screen Capture (XSHM) 2'!
info: PipeWire initialized
info: PipeWire initialized
info: PipeWire initialized
info: Switched to scene 'Firefox'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'TechnicalDifficulties':
info:     - source: 'Image' (image_source)
info:         - filter: 'Crop/Pad' (crop_filter)
info: - scene 'Dicey':
info:     - source: 'videogameinput' (jack_output_capture)
info:     - source: 'Window Capture (Xcomposite)' (xcomposite_input)
info: - scene 'Dark Souls':
info:     - source: 'EldenRing' (xcomposite_input)
info:     - source: 'ds2' (xcomposite_input)
info:     - source: 'ds1' (xcomposite_input)
info: - scene 'Runescape':
info:     - source: 'Runescape OBS Sink' (jack_output_capture)
info:     - source: 'RuneLite' (xcomposite_input)
info:     - source: 'WOLT' (xcomposite_input)
info:         - filter: 'Crop/Pad' (crop_filter)
info:         - filter: 'Color Key' (color_key_filter_v2)
info: - scene 'Firefox':
info:     - source: 'FirefoxInput' (jack_output_capture)
info:     - source: 'Screen Capture (XSHM) 2' (xshm_input)
info:     - source: 'Screen Capture (PipeWire) 3' (pipewire-screen-capture-source)
info: - scene 'Elden Ring X11':
info:     - source: 'Image 2' (image_source)
info:     - source: 'musicinput' (jack_output_capture)
info:     - source: 'Window Capture (Xcomposite) 2' (xcomposite_input)
info: - scene 'Elden Ring Wayland':
info:     - source: 'Image 2' (image_source)
info:     - source: 'videogameinput' (jack_output_capture)
info:     - source: 'musicinput' (jack_output_capture)
info:     - source: 'Screen Capture (PipeWire) 2' (pipewire-desktop-capture-source)
info: - scene 'Scene 2':
info:     - source: 'Screen Capture (PipeWire)' (pipewire-desktop-capture-source)
info: ------------------------------------------------
Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
[New Thread 0x7fff716006c0 (LWP 516442)]
[New Thread 0x7fff70c006c0 (LWP 516443)]
[New Thread 0x7fff67e006c0 (LWP 516444)]
[New Thread 0x7fff674006c0 (LWP 516445)]
[New Thread 0x7fff66a006c0 (LWP 516446)]
info: [pipewire] Screencast session created
info: [pipewire] Screencast session created
info: [pipewire] Screencast session created
info: [pipewire] Asking for monitor
info: [pipewire] Asking for monitor and window
info: [pipewire] Asking for monitor
info: [pipewire] source selected, setting up screencast
info: [pipewire] source selected, setting up screencast
info: [pipewire] source selected, setting up screencast
[New Thread 0x7fff64a006c0 (LWP 516448)]
info: [pipewire] Server version: 1.2.2
info: [pipewire] Library version: 1.2.2
info: [pipewire] Header version: 1.2.1
info: [pipewire] Created stream 0x555557a27f30
info: [pipewire] Stream 0x555557a27f30 state: "connecting" (error: none)
info: [pipewire] Playing stream 0x555557a27f30
[New Thread 0x7fff5be006c0 (LWP 516449)]
info: [pipewire] Stream 0x555557a27f30 state: "paused" (error: none)
info: [pipewire] Server version: 1.2.2
info: [pipewire] Library version: 1.2.2
info: [pipewire] Header version: 1.2.1
info: [pipewire] Created stream 0x555557a558e0
info: [pipewire] Stream 0x555557a558e0 state: "connecting" (error: none)
info: [pipewire] Playing stream 0x555557a558e0
info: [pipewire] Stream 0x555557a558e0 state: "paused" (error: none)
[New Thread 0x7fff5b4006c0 (LWP 516450)]
info: [pipewire] Server version: 1.2.2
info: [pipewire] Library version: 1.2.2
info: [pipewire] Header version: 1.2.1
info: [pipewire] Created stream 0x555557a83fa0
info: [pipewire] Stream 0x555557a83fa0 state: "connecting" (error: none)
info: [pipewire] Playing stream 0x555557a83fa0
info: [pipewire] Stream 0x555557a83fa0 state: "paused" (error: none)
[Thread 0x7fffa20006c0 (LWP 516407) exited]
info: [pipewire] Negotiated format:
info: [pipewire]     Format: 8 (Spa:Enum:VideoFormat:BGRx)
info: [pipewire]     Modifier: 0x0
info: [pipewire]     Size: 3840x2160
info: [pipewire]     Framerate: 0/1
info: [pipewire] Negotiated format:
info: [pipewire]     Format: 8 (Spa:Enum:VideoFormat:BGRx)
info: [pipewire]     Modifier: 0x200000028a37f04
info: [pipewire]     Size: 3840x2160
info: [pipewire]     Framerate: 0/1
info: [pipewire] Negotiated format:
info: [pipewire]     Format: 8 (Spa:Enum:VideoFormat:BGRx)
info: [pipewire]     Modifier: 0x0
info: [pipewire]     Size: 3840x2160
info: [pipewire]     Framerate: 0/1
info: [pipewire] Negotiated format:
info: [pipewire] Negotiated format:
info: [pipewire]     Format: 8 (Spa:Enum:VideoFormat:BGRx)
info: [pipewire]     Format: 8 (Spa:Enum:VideoFormat:BGRx)
info: [pipewire]     Modifier: 0x200000028a37f04
info: [pipewire]     Modifier: 0x0
info: [pipewire]     Size: 3840x2160
info: [pipewire]     Size: 3840x2160
info: [pipewire]     Framerate: 0/1
info: [pipewire]     Framerate: 0/1
info: [pipewire] Stream 0x555557a27f30 state: "streaming" (error: none)
info: [pipewire] Negotiated format:
info: [pipewire]     Format: 8 (Spa:Enum:VideoFormat:BGRx)
info: [pipewire]     Modifier: 0x200000028a37f04
info: [pipewire]     Size: 3840x2160
info: [pipewire]     Framerate: 0/1
info: [pipewire] Stream 0x555557a558e0 state: "streaming" (error: none)
info: [pipewire] Stream 0x555557a83fa0 state: "streaming" (error: none)

Thread 75 "data-loop.0" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff96a006c0 (LWP 516416)]
0x00007fffdbefca65 in ?? () from /usr/lib/libjack.so.0
(gdb) backtrace -full
#0  0x00007fffdbefca65 in ?? () from /usr/lib/libjack.so.0
No symbol table info available.
#1  0x00007fffdbf0363d in jack_port_get_buffer () from /usr/lib/libjack.so.0
No symbol table info available.
#2  0x00007fffe08be18a in jack_process_callback (nframes=512, arg=0x555557091a60)
    at /usr/src/debug/obs-studio/obs-studio-30.2.1-sources/plugins/linux-jack/jack-wrapper.c:80
        i = 0
        jack_buffer = <optimized out>
        data = 0x555557091a60
        current_frames = 32767
        current_usecs = 140737269138973
        next_usecs = 140735720453392
        period_usecs = -2.59657923e+29
        now = 7970078116789
        out = {data = {0x7fff969ff520 "\240\365\237\226\377\177", 0x7fffe08b1373 "\205\300x\t]\303\017\037\200",
            0x7fff969ff5a0 "\340\365\237\226\377\177", 0x7fffdbef91bf "\211E\244\213E\244HiE\260",
            0x7fff969ff560 "\340\365\237\226\377\177", 0x38dbeee324 <error: Cannot access memory at address 0x38dbeee324>,
            0x56052f98 <error: Cannot access memory at address 0x56052f98>, 0x1 <error: Cannot access memory at address 0x1>},
          frames = 7970, speakers = SPEAKERS_STEREO, format = AUDIO_FORMAT_FLOAT_PLANAR, samples_per_sec = 48000,
          timestamp = 140735720453600}
#3  0x00007fffdbefbc89 in ?? () from /usr/lib/libjack.so.0
No symbol table info available.
#4  0x00007fffe08a1fb5 in ?? () from /usr/lib/spa-0.2/support/libspa-support.so
No symbol table info available.
#5  0x00007fffdb56a633 in ?? () from /usr/lib/libpipewire-0.3.so.0
No symbol table info available.
#6  0x00007ffff2ea339d in start_thread (arg=<optimized out>) at pthread_create.c:447
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140735720457920, -2616448876126937598, 140735720457920, -408, 0,
                140737488337760, -2616448876114354686, -2616510605792387582}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0,
              0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#7  0x00007ffff2f2849c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
No locals.
```

**Comment by kkartaltepe** [comment]
pipewire is unsupported, please replicate with a real jack backend.

**Comment by Teascade** [comment]
I'm unable to do that, because my entire desktop linux environment relies on me using pipewire specifically. If this is not a complaint for OBS then, then who shall I make this issue to?

**Comment by kkartaltepe** [comment]
If you cannot test if the issue occurs in jack then its unlikely anyone will be interested in your report, since pipewire will probably just tell you its an obs issue if you cannot prove they diverge from jack's implementation, and im telling you we dont support pipewire since I'm not aware of anyone on our team interested in debugging pipewire's translation layers.
