### ISSUE TITLE
[BUG] Cashes after choosing a microphone in Settings/Audio/Mix/Auxiliary Audio and pressing "Apply"

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#2627]
## Platform
Operating system and version: FreeBSD 12
OBS Studio version: 25.0.1

## Expected Behavior
Accept a new value

## Current Behavior
SEGV

## Steps to Reproduce
See the subject.

## Additional information
Console messages and stack trace:
```
info: xshm-input: Geometry 1920x1080 @ 0,0
debug: source 'Screen Capture (XSHM)' (xshm_input) created
info: v4l2-input: Start capture from /dev/video0
info: v4l2-input: Input: 0
info: v4l2-input: Resolution: 640x480
info: v4l2-input: Pixelformat: VYUY
info: v4l2-input: Linesize: 1280 Bytes
info: v4l2-input: Framerate: 30.00 fps
[New LWP 100713 of process 84147]
[New LWP 102883 of process 84147]
debug: source 'Video Capture Device (V4L2)' (v4l2_input) created
[New LWP 102995 of process 84147]
debug: source 'Scene 2' (scene) created
info: Switched to scene 'Scene 1'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene 1':
info:     - source: 'Screen Capture (XSHM)' (xshm_input)
info:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
info: - scene 'Scene 2':
info: ------------------------------------------------
[New LWP 100402 of process 84147]
info: [obs-websocket] server started successfully on port 4444
info: [obs-websocket] io thread started
Attempted path: share/obs/obs-studio/images/overflow.png
Attempted path: /usr/local/share/obs/obs-studio/images/overflow.png
[LWP 101756 of process 84147 exited]
info: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds (source: Desktop Audio)

info: adding 23 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Mic/Aux)

[New LWP 102996 of process 84147]
[LWP 102996 of process 84147 exited]
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/local/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/
Attempted path: /usr/local/share/obs/obs-studio/themes/
info: pulse-input: Stopped recording from 'oss_input.dsp6'
info: pulse-input: Got 475 packets with 486400 frames
info: pulse-input: Server name: 'pulseaudio 13.0'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'oss_input.dsp6'
info: Settings changed (audio)
info: ------------------------------------------------

Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000080276c184 in QAbstractButton::isChecked() const () from /usr/local/lib/qt5/libQt5Widgets.so.5
(gdb) bt
#0  0x000000080276c184 in QAbstractButton::isChecked() const () from /usr/local/lib/qt5/libQt5Widgets.so.5
#1  0x000000000046b1a1 in OBSBasicSettings::SaveSettings (this=0x7fffffffcbe8) at /usr/ports/multimedia/obs-studio/work/obs-studio-25.0.1/UI/window-basic-settings.cpp:3539
#2  0x000000000046b808 in OBSBasicSettings::on_buttonBox_clicked (this=0x7fffffffcbe8, button=0x819177550)
    at /usr/ports/multimedia/obs-studio/work/obs-studio-25.0.1/UI/window-basic-settings.cpp:3616
#3  0x0000000000355a8a in OBSBasicSettings::qt_static_metacall (_o=0x7fffffffcbe8, _c=QMetaObject::InvokeMetaMethod, _id=10, _a=0x7fffffffbde0)
    at UI/obs_autogen/EWIEGA46WW/moc_window-basic-settings.cpp:518
#4  0x0000000000356345 in OBSBasicSettings::qt_metacall (this=0x7fffffffcbe8, _c=QMetaObject::InvokeMetaMethod, _id=10, _a=0x7fffffffbde0)
    at UI/obs_autogen/EWIEGA46WW/moc_window-basic-settings.cpp:636
#5  0x000000080366c09b in QMetaObject::activate(QObject*, int, int, void**) () from /usr/local/lib/qt5/libQt5Core.so.5
#6  0x0000000802815ac4 in ?? () from /usr/local/lib/qt5/libQt5Widgets.so.5
#7  0x000000080366c391 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/local/lib/qt5/libQt5Core.so.5
#8  0x000000080276b9f2 in ?? () from /usr/local/lib/qt5/libQt5Widgets.so.5
#9  0x000000080276b88c in ?? () from /usr/local/lib/qt5/libQt5Widgets.so.5
#10 0x000000080276c863 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/local/lib/qt5/libQt5Widgets.so.5
#11 0x00000008026be127 in QWidget::event(QEvent*) () from /usr/local/lib/qt5/libQt5Widgets.so.5
#12 0x0000000802682a51 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/local/lib/qt5/libQt5Widgets.so.5
#13 0x0000000802685a43 in QApplication::notify(QObject*, QEvent*) () from /usr/local/lib/qt5/libQt5Widgets.so.5
#14 0x0000000803639362 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/local/lib/qt5/libQt5Core.so.5
#15 0x0000000802683413 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
   from /usr/local/lib/qt5/libQt5Widgets.so.5
#16 0x00000008026dd898 in ?? () from /usr/local/lib/qt5/libQt5Widgets.so.5
#17 0x00000008026dc597 in ?? () from /usr/local/lib/qt5/libQt5Widgets.so.5
#18 0x0000000802682a51 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/local/lib/qt5/libQt5Widgets.so.5
#19 0x0000000802683f98 in QApplication::notify(QObject*, QEvent*) () from /usr/local/lib/qt5/libQt5Widgets.so.5
#20 0x0000000803639362 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/local/lib/qt5/libQt5Core.so.5
#21 0x0000000802c58180 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/local/lib/qt5/libQt5Gui.so.5
#22 0x0000000802c3e55c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/lib/qt5/libQt5Gui.so.5
#23 0x000000080b17c7ff in ?? () from /usr/local/lib/qt5/libQt5XcbQpa.so.5
#24 0x00000008067027d7 in g_main_context_dispatch () from /usr/local/lib/libglib-2.0.so.0
#25 0x0000000806702b9a in ?? () from /usr/local/lib/libglib-2.0.so.0
#26 0x0000000806702c54 in g_main_context_iteration () from /usr/local/lib/libglib-2.0.so.0
#27 0x0000000803691e06 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/lib/qt5/libQt5Core.so.5
#28 0x0000000803634a0e in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/lib/qt5/libQt5Core.so.5
#29 0x00000008028805c6 in QDialog::exec() () from /usr/local/lib/qt5/libQt5Widgets.so.5
#30 0x00000000003e00ec in OBSBasic::on_action_Settings_triggered (this=0x80b36cc00) at /usr/ports/multimedia/obs-studio/work/obs-studio-25.0.1/UI/window-basic-main.cpp:4090
#31 0x0000000000353bbd in OBSBasic::qt_static_metacall (_o=0x80b36cc00, _c=QMetaObject::InvokeMetaMethod, _id=112, _a=0x7fffffffd3b0)
    at UI/obs_autogen/EWIEGA46WW/moc_window-basic-main.cpp:1128
#32 0x0000000000354ea8 in OBSBasic::qt_metacall (this=0x80b36cc00, _c=QMetaObject::InvokeMetaMethod, _id=112, _a=0x7fffffffd3b0) at UI/obs_autogen/EWIEGA46WW/moc_window-basic-main.cpp:1345
#33 0x000000080366c09b in QMetaObject::activate(QObject*, int, int, void**) () from /usr/local/lib/qt5/libQt5Core.so.5
#34 0x0000000802679979 in QAction::activate(QAction::ActionEvent) () from /usr/local/lib/qt5/libQt5Widgets.so.5
#35 0x00000008027fcdcd in ?? () from /usr/local/lib/qt5/libQt5Widgets.so.5
#36 0x00000008027fa3cc in ?? () from /usr/local/lib/qt5/libQt5Widgets.so.5
#37 0x000000080280166e in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/local/lib/qt5/libQt5Widgets.so.5
#38 0x00000008026be127 in QWidget::event(QEvent*) () from /usr/local/lib/qt5/libQt5Widgets.so.5
#39 0x0000000802801cf5 in QMenu::event(QEvent*) () from /usr/local/lib/qt5/libQt5Widgets.so.5
#40 0x0000000802682a51 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/local/lib/qt5/libQt5Widgets.so.5
#41 0x0000000802685a43 in QApplication::notify(QObject*, QEvent*) () from /usr/local/lib/qt5/libQt5Widgets.so.5
```

There's null dereferencing:
```
(gdb) down
#1  0x000000000046b1a1 in OBSBasicSettings::SaveSettings (this=0x7fffffffcbe8) at /usr/ports/multimedia/obs-studio/work/obs-studio-25.0.1/UI/window-basic-settings.cpp:3539
3539			(ui->browserHWAccel->isChecked() != prevBrowserAccel);
(gdb) p ui
$4 = std::unique_ptr<Ui::OBSBasicSettings> = 0x810463000
(gdb) p ui->browserHWAccel
$5 = (QCheckBox *) 0x0
```

**Comment by kkartaltepe** [comment]
Fixed in 25.0.3, 25.0.1 and 25.0.2 are unstable on linux.
