### ISSUE TITLE
OBS 26.1.2 crashes on FreeBSD - Thread 175 "libobs: graphics th" received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by Martinfx** [obsproject/obs-studio#4090]
### Platform

Operating system and version: FreeBSD  12.1-RELEASE-p11 FreeBSD 12.1-RELEASE-p11 GENERIC  amd64
OBS Studio version: 26.1.2 . 
Xorg: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.9.

This bug has been report in FreeBSD bugzilla

### Expected Behavior

The application should start normally and display the user interface.

### Current Behavior

The application quits unexpectedly.
Thread 175 "libobs: graphics th" received signal SIGSEGV, Segmentation fault.

[https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252794](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252794)
[obs_gdb_backtrace.txt](https://github.com/obsproject/obs-studio/files/5829126/obs_gdb_backtrace.txt)

Log files do not contain any useful information, logging simply cuts out after plugin initialization and the scenes and sources list.
Steps to Reproduce

    Install OBS 26.1.2
    Start the application.

### Additional information

1.     Install OBS 26.1.2
2.     Start the application.
3.     Automatic settings for stream
4.     Exit application -> crash

```
info: ==== Shutting down ==================================================
debug: private source 'Cut' destroyed
debug: source 'Scene' destroyed
debug: source 'Window Capture (Xcomposite)' destroyed
debug: private source 'Fade' destroyed
debug: source 'Desktop Audio' destroyed
info: pulse-input: Stopped recording from 'oss_output.dsp0.monitor'
info: pulse-input: Got 5935 packets with 6077440 frames
debug: source 'Mic/Aux' destroyed
info: pulse-input: Stopped recording from 'oss_input.dsp0'
info: pulse-input: Got 5931 packets with 6073344 frames
[LWP 102242 of process 23670 exited]
info: All scene data cleared
info: ------------------------------------------------
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
debug: service 'default_service' destroyed
debug: encoder 'simple_archive_aac' destroyed
debug: encoder 'simple_h264_stream' destroyed
debug: encoder 'simple_aac' destroyed
debug: output 'simple_stream' destroyed
debug: output 'simple_file_output' destroyed
error: Failed to fetch parent window geometry!
error: X Error: BadDrawable (invalid Pixmap or Window parameter), Major opcode: 130, Minor opcode: BadWindow (invalid Window parameter), Serial: 45288
error: X Error: BadDrawable (invalid Pixmap or Window parameter), Major opcode: BadIDChoice (invalid resource ID chosen for this connection), Minor opcode: 0, Serial: 45290
error: Failed to fetch parent window geometry!
--Type <RET> for more, q to quit, c to continue without paging--

Thread 175 "libobs: graphics th" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 102408 of process 23670]
0x000000080df7cd55 in ?? () from /usr/local/lib/dri/swrast_dri.so
(gdb) 
(gdb) bt
#0  0x000000080df7cd55 in ?? () from /usr/local/lib/dri/swrast_dri.so
#1  0x000000080df80e5f in ?? () from /usr/local/lib/dri/swrast_dri.so
#2  0x000000080df7d73c in ?? () from /usr/local/lib/dri/swrast_dri.so
#3  0x000000080df7d644 in ?? () from /usr/local/lib/dri/swrast_dri.so
#4  0x000000080d90a99b in ?? () from /usr/local/lib/dri/swrast_dri.so
#5  0x00000008071fcc78 in ?? () from /usr/local/lib/libGL.so.1
#6  0x00000008071ff09a in glXSwapBuffers () from /usr/local/lib/libGL.so.1
#7  0x000000080cf380a8 in device_present (device=0x80bbbb820) at /usr/ports/multimedia/obs-studio/work/obs-studio-26.1.2/libobs-opengl/gl-x11.c:578
#8  0x0000000802d2b37d in gs_present () at /usr/ports/multimedia/obs-studio/work/obs-studio-26.1.2/libobs/graphics/graphics.c:1816
#9  0x0000000802dab3af in render_display (display=0x818eaa3a0) at /usr/ports/multimedia/obs-studio/work/obs-studio-26.1.2/libobs/obs-display.c:228
#10 0x0000000802db7c64 in render_displays () at /usr/ports/multimedia/obs-studio/work/obs-studio-26.1.2/libobs/obs-video.c:97
#11 0x0000000802db74b1 in obs_graphics_thread_loop (context=0x7fffd89c2f70) at /usr/ports/multimedia/obs-studio/work/obs-studio-26.1.2/libobs/obs-video.c:979
#12 0x0000000802db7f31 in obs_graphics_thread (param=0x80ab45020) at /usr/ports/multimedia/obs-studio/work/obs-studio-26.1.2/libobs/obs-video.c:1050
#13 0x0000000802577736 in thread_start (curthread=0x8085b8300) at /usr/src/lib/libthr/thread/thr_create.c:292
#14 0x0000000000000000 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7fffd89c3000
```

**Comment by Martinfx** [comment]
@WizardCM your label "Linux" is bad. This is FreeBSD OS.

**Comment by kkartaltepe** [comment]
This was probably fixed on master recently, can you please test again?

**Comment by Martinfx** [comment]
@kkartaltepe bug has been fixed. Thank you.
