### ISSUE TITLE
OBS v27 Linux segfaults on start

### ISSUE THREAD

**Issue by djahandarie** [obsproject/obs-studio#4852]
### Operating System Info

Other

### Other OS

NixOS

### OBS Studio Version

27.0.0

### OBS Studio Log URL

Unknown

### Expected Behavior

Not segv

### Current Behavior

```(gdb) bt
#0  0x00007fff9f9fe510 in base::internal::SequenceLocalStorageMap::Get(int) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#1  0x00007fff9fa54795 in mojo::internal::MessageDispatchContext::MessageDispatchContext(mojo::Message*) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#2  0x00007fffa065ffe4 in service_manager::mojom::ServiceManagerListenerStubDispatch::Accept(service_manager::mojom::ServiceManagerListener*, mojo::Message*) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#3  0x00007fff9fa4ceb8 in mojo::internal::MultiplexRouter::ProcessIncomingMessage(mojo::internal::MultiplexRouter::MessageWrapper*, mojo::internal::MultiplexRouter::ClientCallBehavior, base::SequencedTaskRunner*) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#4  0x00007fff9fa4c8e7 in mojo::internal::MultiplexRouter::Accept(mojo::Message*) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#5  0x00007fff9fa46921 in mojo::Connector::DispatchMessage(mojo::Message) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#6  0x00007fff9fa4703b in mojo::Connector::ReadAllAvailableMessages() ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#7  0x00007fff9fa5a425 in mojo::SimpleWatcher::OnHandleReady(int, unsigned int, mojo::HandleSignalsState const&) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#8  0x00007fff9f9d80bd in base::TaskAnnotator::RunTask(char const*, base::PendingTask*) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#9  0x00007fff9f9e744c in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*, bool*) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#10 0x00007fff9f9e7899 in non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() () from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#11 0x00007fff9f9a85ff in base::(anonymous namespace)::WorkSourceDispatch(_GSource*, int (*)(void*), void*) ()
   from /nix/store/liyzbyv56hvad5hzm04lsl004piax9aq-obs-studio-27.0.0//lib/obs-plugins/libcef.so
#12 0x00007fffefe415ab in g_main_context_dispatch ()
   from /nix/store/dcb3cyba5wl6qimv6vwdpbi0kg0g1nlb-glib-2.68.2/lib/libglib-2.0.so.0
#13 0x00007fffefe41858 in g_main_context_iterate.constprop ()
   from /nix/store/dcb3cyba5wl6qimv6vwdpbi0kg0g1nlb-glib-2.68.2/lib/libglib-2.0.so.0
#14 0x00007fffefe4190f in g_main_context_iteration ()
   from /nix/store/dcb3cyba5wl6qimv6vwdpbi0kg0g1nlb-glib-2.68.2/lib/libglib-2.0.so.0
#15 0x00007ffff555f520 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /nix/store/z8s9ggc72xkhv9xfxk88q08rrylcxqjf-qtbase-5.15.2/lib/libQt5Core.so.5
#16 0x00007ffff5505d7b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /nix/store/z8s9ggc72xkhv9xfxk88q08rrylcxqjf-qtbase-5.15.2/lib/libQt5Core.so.5
#17 0x00007ffff550e360 in QCoreApplication::exec() ()
   from /nix/store/z8s9ggc72xkhv9xfxk88q08rrylcxqjf-qtbase-5.15.2/lib/libQt5Core.so.5
#18 0x0000000000482306 in main ()
```

### Steps to Reproduce

Unknown

### Anything else we should know?

Started after upgrading to v27

**Comment by notr1ch** [comment]
As NixOS is not an officially supported distribution, please raise this with the NixOS packager.

**Comment by djahandarie** [comment]
In case anyone else runs across this, I temporarily resolved the issue by removing all my scenes (since one had a browser embed in it, and the segv seemingly was happening in libcef, which is chrome).
