### ISSUE TITLE
[Linux] OBS crashes when I try to record my screen on Wayland session of KDE Plasma desktop environment

### ISSUE THREAD

**Issue by glaubersm** [obsproject/obs-studio#5141]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/WQGKx0KPA35jfQUG

### Expected Behavior

no crash

### Current Behavior

OBS crashes when I try to record my screen on Wayland session of KDE Plasma.

### Steps to Reproduce

1. try to record your screen on Wayland session of KDE Plasma
2.
3.
...

### Anything else we should know?

backtrace of the crash generated with GDB debugger

```

Thread 19 (Thread 0x7fea499c3640 (LWP 61633)):
#0  0x00007fea8588ab2f in poll () at /usr/lib/libc.so.6
#1  0x00007fea784f1ae4 in  () at /usr/lib/libpulse.so.0
#2  0x00007fea784db4b9 in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007fea784e5709 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007fea784e57c1 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#5  0x00007fea784f5c9e in  () at /usr/lib/libpulse.so.0
#6  0x00007fea7729c403 in  () at /usr/lib/pulseaudio/libpulsecommon-15.0.so
#7  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 18 (Thread 0x7fea51261640 (LWP 61628)):
#0  0x00007fea859788ca in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007fea85974ae8 in __new_sem_wait_slow64.constprop.0 () at /usr/lib/libpthread.so.0
#2  0x00007fea6000c223 in defer_thread (unused=<optimized out>) at /usr/src/debug/obs-studio-27.0.1/deps/obs-scripting/obs-scripting.c:89
#3  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 17 (Thread 0x7fea52f7d640 (LWP 61626)):
#0  0x00007fea859788ca in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007fea85974ae8 in __new_sem_wait_slow64.constprop.0 () at /usr/lib/libpthread.so.0
#2  0x00007fea8697a98f in video_thread (param=0x563108d0baa0) at /usr/src/debug/obs-studio-27.0.1/libobs/media-io/video-io.c:183
#3  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 16 (Thread 0x7fea4bfff640 (LWP 61623)):
#0  0x00007fea859788ca in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007fea85972270 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007fea614a5ecc in  () at /usr/lib/dri/i965_dri.so
#3  0x00007fea614a5888 in  () at /usr/lib/dri/i965_dri.so
#4  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 15 (Thread 0x7fea53fff640 (LWP 61622)):
#0  0x00007fea859788ca in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007fea85972270 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007fea614a5ecc in  () at /usr/lib/dri/i965_dri.so
#3  0x00007fea614a5888 in  () at /usr/lib/dri/i965_dri.so
#4  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 14 (Thread 0x7fea608fa640 (LWP 61621)):
#0  0x00007fea859788ca in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007fea85972270 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007fea614a5ecc in  () at /usr/lib/dri/i965_dri.so
#3  0x00007fea614a5888 in  () at /usr/lib/dri/i965_dri.so
#4  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 13 (Thread 0x7fea610fb640 (LWP 61620)):
#0  0x00007fea859788ca in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007fea85972270 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007fea614a5ecc in  () at /usr/lib/dri/i965_dri.so
#3  0x00007fea614a5888 in  () at /usr/lib/dri/i965_dri.so
#4  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 12 (Thread 0x7fea63fff640 (LWP 61618)):
#0  0x00007fea859788ca in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007fea85972574 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007fea85dcf000 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /usr/lib/libQt5Core.so.5
#3  0x00007fea85dcc4a8 in  () at /usr/lib/libQt5Core.so.5
#4  0x00007fea85dc8fef in  () at /usr/lib/libQt5Core.so.5
#5  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 11 (Thread 0x7fea70913640 (LWP 61617)):
#0  0x00007fea859788ca in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007fea85972574 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007fea85dcf000 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /usr/lib/libQt5Core.so.5
#3  0x00007fea85dcc4a8 in  () at /usr/lib/libQt5Core.so.5
#4  0x00007fea85dc8fef in  () at /usr/lib/libQt5Core.so.5
#5  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 10 (Thread 0x7fea71d51640 (LWP 61616)):
#0  0x00007fea8588ab2f in poll () at /usr/lib/libc.so.6
#1  0x00007fea848b5b29 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fea84861693 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007fea786458c8 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007fea848902c1 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7fea72574640 (LWP 61615)):
#0  0x00007fea8588ab2f in poll () at /usr/lib/libc.so.6
#1  0x00007fea848b5b29 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fea8485f871 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fea8485f8c2 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007fea848902c1 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 8 (Thread 0x7fea750c8100 (LWP 61613)):
#0  0x00007fea859788ca in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007fea85972270 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007fea88bb367c in wl_display_read_events () at /usr/lib/libwayland-client.so.0
#3  0x00007fea74cc7933 in QtWaylandClient::QWaylandDisplay::flushRequests() () at /usr/lib/libQt5WaylandClient.so.5
#4  0x00007fea85feb790 in  () at /usr/lib/libQt5Core.so.5
#5  0x00007fea8600d06d in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#6  0x00007fea85fb2d1c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#7  0x00007fea85fbb284 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#8  0x0000563106e590a7 in run_program (argv=0x7ffce3d58918, argc=<optimized out>, logFile=...) at /usr/src/debug/obs-studio-27.0.1/UI/obs-app.cpp:2087
#9  main(int, char**) (argc=<optimized out>, argv=0x7ffce3d58918) at /usr/src/debug/obs-studio-27.0.1/UI/obs-app.cpp:2762

Thread 7 (Thread 0x7fea168ee640 (LWP 61642)):
#0  0x00007fea8589592e in epoll_wait () at /usr/lib/libc.so.6
#1  0x00007fea5039ea41 in  () at /usr/lib/spa-0.2/support/libspa-support.so
#2  0x00007fea50397b24 in  () at /usr/lib/spa-0.2/support/libspa-support.so
#3  0x00007fea500fd866 in  () at /usr/lib/libpipewire-0.3.so.0
#4  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7fea4a27a640 (LWP 61641)):
#0  0x00007fea8589592e in epoll_wait () at /usr/lib/libc.so.6
#1  0x00007fea5039ea41 in  () at /usr/lib/spa-0.2/support/libspa-support.so
#2  0x00007fea50397b24 in  () at /usr/lib/spa-0.2/support/libspa-support.so
#3  0x00007fea500c45b0 in  () at /usr/lib/libpipewire-0.3.so.0
#4  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7fea51f90640 (LWP 61627)):
#0  0x00007fea8588ab2f in poll () at /usr/lib/libc.so.6
#1  0x00007fea88bb3f46 in wl_display_dispatch_queue () at /usr/lib/libwayland-client.so.0
#2  0x00007fea6251c325 in  () at /usr/lib/libEGL_mesa.so.0
#3  0x00007fea625089a2 in  () at /usr/lib/libEGL_mesa.so.0
#4  0x00007fea624fec04 in  () at /usr/lib/libEGL_mesa.so.0
#5  0x00007fea600dd332 in gl_wayland_egl_device_present (device=<optimized out>) at /usr/src/debug/obs-studio-27.0.1/libobs-opengl/gl-wayland-egl.c:319
#6  0x00007fea869dd309 in render_displays () at /usr/src/debug/obs-studio-27.0.1/libobs/obs-video.c:97
#7  obs_graphics_thread_loop (context=context@entry=0x7fea51f8f440) at /usr/src/debug/obs-studio-27.0.1/libobs/obs-video.c:981
#8  0x00007fea869de2e9 in obs_graphics_thread (param=<optimized out>) at /usr/src/debug/obs-studio-27.0.1/libobs/obs-video.c:1052
#9  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#10 0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fea537fe640 (LWP 61624)):
#0  0x00007fea8585da95 in clock_nanosleep@GLIBC_2.2.5 () at /usr/lib/libc.so.6
#1  0x00007fea85862c77 in nanosleep () at /usr/lib/libc.so.6
#2  0x00007fea8588da99 in usleep () at /usr/lib/libc.so.6
#3  0x00007fea8698fcec in os_sleep_ms (duration=<optimized out>) at /usr/src/debug/obs-studio-27.0.1/libobs/util/platform-nix.c:184
#4  0x00007fea8697bf9a in audio_thread (param=0x563108c3d1e0) at /usr/src/debug/obs-studio-27.0.1/libobs/media-io/audio-io.c:218
#5  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7fea62dee640 (LWP 61619)):
#0  0x00007fea859788ca in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007fea85972574 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#2  0x00007fea8698f239 in os_event_timedwait (event=0x5631086baf40, milliseconds=milliseconds@entry=25) at /usr/src/debug/obs-studio-27.0.1/libobs/util/threading-posix.c:121
#3  0x00007fea869c4a05 in obs_hotkey_thread (arg=<optimized out>) at /usr/src/debug/obs-studio-27.0.1/libobs/obs-hotkey.c:1383
#4  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fea72d75640 (LWP 61614)):
#0  0x00007fea8588ab2f in poll () at /usr/lib/libc.so.6
#1  0x00007fea848b5b29 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fea8485f871 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fea8600cfd6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007fea85fb2d1c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007fea85dc7e12 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007fea74bd9ae8 in  () at /usr/lib/libQt5DBus.so.5
#7  0x00007fea85dc8fef in  () at /usr/lib/libQt5Core.so.5
#8  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7fea160c5640 (LWP 61646)):
#0  0x00007fea8779d515 in  () at /usr/lib/libavcodec.so.58
#1  0x00007fea8786efb5 in avcodec_open2 () at /usr/lib/libavcodec.so.58
#2  0x00007fea5032a75b in open_video_codec (data=0x56310948f510) at /usr/src/debug/obs-studio-27.0.1/plugins/obs-ffmpeg/obs-ffmpeg-output.c:154
#3  create_video_stream (data=0x56310948f510) at /usr/src/debug/obs-studio-27.0.1/plugins/obs-ffmpeg/obs-ffmpeg-output.c:254
#4  init_streams (data=0x56310948f510) at /usr/src/debug/obs-studio-27.0.1/plugins/obs-ffmpeg/obs-ffmpeg-output.c:377
#5  ffmpeg_data_init (data=data@entry=0x56310948f510, config=config@entry=0x7fea160c43d0) at /usr/src/debug/obs-studio-27.0.1/plugins/obs-ffmpeg/obs-ffmpeg-output.c:607
#6  0x00007fea5032b22f in try_connect (output=<optimized out>) at /usr/src/debug/obs-studio-27.0.1/plugins/obs-ffmpeg/obs-ffmpeg-output.c:1127
#7  start_thread (data=0x56310948f500) at /usr/src/debug/obs-studio-27.0.1/plugins/obs-ffmpeg/obs-ffmpeg-output.c:1167
#8  0x00007fea8596c259 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007fea858955e3 in clone () at /usr/lib/libc.so.6

```

**Comment by kkartaltepe** [comment]
Your log is missing the context of what thread faulted. Also please provide your encoder settings. maybe related to #3254 but also could just be you failed to update your system correctly as ffmpeg abi isnt super stable and you are on arch.

**Comment by glaubersm** [comment]
encoder settings

![encoder](https://user-images.githubusercontent.com/15967631/129640168-3b458edd-4c22-4e94-8199-92cae2ae89db.png)

**Comment by kkartaltepe** [comment]
Please provide a backtrace of the crashing thread if this is still happening and we can reopen this.
