### ISSUE TITLE
Segmentation fault during eglInitialize

### ISSUE THREAD

**Issue by marceloslacerda** [obsproject/obs-studio#5613]
### Operating System Info

Ubuntu 21.04

### OBS Studio Version

27.1.3

### OBS Studio Log URL

There's none

### Expected Behavior

obs starts when I run obs

### Current Behavior

obs crashes with a segfault

### Steps to Reproduce

1. Follow the ubuntu install instructions: https://obsproject.com/wiki/install-instructions#ubuntumint-installation
2. Run obs from the terminal

### Anything else we should know?

This is the first time running obs on this machine it's an upgrade from ubuntu 21.04 (previously ubuntu 20.10).

```
$ obs
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: Platform: Wayland
info: CPU Name: AMD FX(tm)-8300 Eight-Core Processor
info: CPU Speed: 1400.000MHz
info: Physical Cores: 4, Logical Cores: 8
info: Physical Memory: 15959MB Total, 12893MB Free
info: Kernel Version: Linux 5.13.0-22-generic
info: Distribution: "Ubuntu" "21.10"
info: Session Type: wayland
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 27.1.3 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Using EGL/Wayland
Segmentation fault (core dumped)
```
Setting `QT_QPA_PLATFORM=wayland` produces the exact same log

**Comment by notr1ch** [comment]
Please also include the stack trace from gdb: https://stackoverflow.com/questions/5745215/getting-stacktrace-from-core-dump

**Comment by marceloslacerda** [comment]
Is this it?

```(gdb) bt
#0  0x00007f392fe03794 in xcb_connection_has_error () at /lib/x86_64-linux-gnu/libxcb.so.1
#1  0x00007f3910c72b5e in  () at /opt/amdgpu/lib/x86_64-linux-gnu/libEGL.so.1
#2  0x00007f3910c748a4 in  () at /opt/amdgpu/lib/x86_64-linux-gnu/libEGL.so.1
#3  0x00007f3910c6d300 in  () at /opt/amdgpu/lib/x86_64-linux-gnu/libEGL.so.1
#4  0x00007f3910c6445c in eglInitialize () at /opt/amdgpu/lib/x86_64-linux-gnu/libEGL.so.1
#5  0x00007f3910d19fd3 in  () at /lib/libobs-opengl.so.0
#6  0x00007f3910d1fe39 in device_create () at /lib/libobs-opengl.so.0
#7  0x00007f3935e3e3f3 in gs_create () at /lib/libobs.so.0
#8  0x00007f3935e86cdd in obs_reset_video () at /lib/libobs.so.0
#9  0x0000560366b96387 in  ()
#10 0x0000560366b84617 in  ()
#11 0x0000560366b32e97 in main ()
```

**Comment by kkartaltepe** [comment]
Likely you failed to upgrade. After upgrading you must manually migrate PPA's to the new version, if you dont do that things will break. Please ensure you updated your ppa to the match the new version and have reinstalled obs.

**Comment by marceloslacerda** [comment]
Nah I have installed obs after the upgrades it's picking up the correct repository. By the way using the package that is shipped by the ubuntu teams does work without crashing.

**Comment by marceloslacerda** [comment]
Adding to my previous post. It launches and the wizard runs without crashing. There's no pipewire option when launching from gnome. If I try to launch from a terminal with QT_QPA_PLATFORM=wayland obs, them it seems to crash similarly to the previous attempt.

```
#0  0x00007f203615910b in XGetXCBConnection ()
   from /lib/x86_64-linux-gnu/libX11-xcb.so.1
[Current thread is 1 (Thread 0x7f203a9f63c0 (LWP 23427))]
(gdb) bt
#0  0x00007f203615910b in XGetXCBConnection ()
    at /lib/x86_64-linux-gnu/libX11-xcb.so.1
#1  0x00007f200ecaac28 in  () at /opt/amdgpu/lib/x86_64-linux-gnu/libEGL.so.1
#2  0x00007f200ecac8a4 in  () at /opt/amdgpu/lib/x86_64-linux-gnu/libEGL.so.1
#3  0x00007f200eca5300 in  () at /opt/amdgpu/lib/x86_64-linux-gnu/libEGL.so.1
#4  0x00007f200ec9c45c in eglInitialize ()
    at /opt/amdgpu/lib/x86_64-linux-gnu/libEGL.so.1
#5  0x00007f200ed52123 in  () at /lib/x86_64-linux-gnu/libobs-opengl.so.0
#6  0x00007f200ed584f9 in device_create ()
    at /lib/x86_64-linux-gnu/libobs-opengl.so.0
#7  0x00007f203be9af5c in gs_create () at /lib/x86_64-linux-gnu/libobs.so.0
#8  0x00007f203beed160 in obs_reset_video ()
    at /lib/x86_64-linux-gnu/libobs.so.0
#9  0x000055b419a54117 in  ()
#10 0x000055b419a42742 in  ()
#11 0x000055b419a066ff in main ()
```

**Comment by kkartaltepe** [comment]
> Nah I have installed obs after the upgrades

This is insufficient, as explained the repository must be rewritten (by manually editing the file) after upgrading versions, or you must entirely remove the ppa. Either way the backtrace makes it clear that your system is somehow broken.

> the package that is shipped by the ubuntu teams does work without crashing.

It is very unsurprising that using the correct repository for your release works.

**Comment by marceloslacerda** [comment]
>This is insufficient, as explained the repository must be rewritten (by manually editing the file) after upgrading versions, or you must entirely remove the ppa.
I installed the ppa after the upgrade

```
deb http://ppa.launchpad.net/obsproject/obs-studio/ubuntu/ impish main
deb-src http://ppa.launchpad.net/obsproject/obs-studio/ubuntu/ impish main
```

>Either way the backtrace makes it clear that your system is somehow broken.
Can you be more specific?


> It is very unsurprising that using the correct repository for your release works.
I have already stated that the version shipped by the ubuntu team does startup but doesn't include any screen capture mechanism compatible with wayland and trying to force obs to use wayland crashes the software.

**Comment by kkartaltepe** [comment]
Your next step is probably to figure out why your obs is not respecting the platform its running on, and trying to load X11 after reporting you running on wayland.

**Comment by kkartaltepe** [comment]
> >  Either way the backtrace makes it clear that your system is somehow broken.
> Can you be more specific?

> If I try to launch from a terminal with QT_QPA_PLATFORM=wayland obs

 ```
#0  0x00007f203615910b in XGetXCBConnection ()
    at /lib/x86_64-linux-gnu/libX11-xcb.so.1
#1  0x00007f200ecaac28 in  () at /opt/amdgpu/lib/x86_64-linux-gnu/libEGL.so.1
#2  0x00007f200ecac8a4 in  () at /opt/amdgpu/lib/x86_64-linux-gnu/libEGL.so.1
#3  0x00007f200eca5300 in  () at /opt/amdgpu/lib/x86_64-linux-gnu/libEGL.so.1
#4  0x00007f200ec9c45c in eglInitialize ()
```

Such a call stack is should not be possible with the obs code as written and released.

**Comment by kkartaltepe** [comment]
Someone else recently replicated this issue on mesa devel drivers which went away when reverting to stable mesa drivers. So im going to mark this confirmed and as a dependency issue.

**Comment by kkartaltepe** [comment]
![image](https://user-images.githubusercontent.com/526419/145660179-fb8dd63e-832e-4be8-b645-34616c4c0df6.png)
With terrible OCR job as follows

```
Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
in XGetXCBConnection () from /usr/lib/x86_64-lLinux-gnu/libX11-xcb.so.1
(gdb) backtrace
#0 in XGetXCBConnection () at /usr/lib/x86_64-Linux-gnu/libX11-xcb.so.1
#1 in dri2_get_xcb_connection.constprop () at /home/alosarjos/.local/share/mesa-git/1lib64/libEGL.so.1
#2 in dri2_initialize_x11 () at /home/alosarjos/.local/share/mesa-git/1ib64/1ibEGL.so.1
#3 in dri2_initialize () at /home/alosarjos/.local/share/mesa-git/lib64/libEGL.so.1
#4 in eglInitialize () at /home/alosarjos/.local/share/mesa-git/1ib64/libEGL.so.1
#5 in () at /app/lib/libobs-opengl.so.d
#6 in device_create () at /app/lib/libobs-opengl.so.0
#7 in gs_create () at /app/lib/libobs.so.0
#8 in obs_reset_video () at /app/lib/libobs.so.0
#9 in ()
#10 in ()
#11 in ()
#12 in main ()
```

**Comment by marceloslacerda** [comment]
Hmm I haven't changed my drivers from the default repos. I'm not that adventurous.
Btw these are my mesa drivers installed.

```
ii  mesa-amdgpu-omx-drivers:amd64              1:21.2.0-1290604                           amd64        Mesa OpenMAX video drivers
ii  mesa-amdgpu-va-drivers:amd64               1:21.2.0-1290604                           amd64        Mesa VA-API video acceleration drivers
ii  mesa-amdgpu-va-drivers:i386                1:21.2.0-1290604                           i386         Mesa VA-API video acceleration drivers
ii  mesa-amdgpu-vdpau-drivers:amd64            1:21.2.0-1290604                           amd64        Mesa VDPAU video acceleration drivers
ii  mesa-amdgpu-vdpau-drivers:i386             1:21.2.0-1290604                           i386         Mesa VDPAU video acceleration drivers
ii  mesa-utils                                 8.4.0-1build1                              amd64        Miscellaneous Mesa GL utilities
ii  mesa-va-drivers:amd64                      21.2.2-1ubuntu1                            amd64        Mesa VA-API video acceleration drivers
ii  mesa-va-drivers:i386                       21.2.2-1ubuntu1                            i386         Mesa VA-API video acceleration drivers
ii  mesa-vdpau-drivers:amd64                   21.2.2-1ubuntu1                            amd64        Mesa VDPAU video acceleration drivers
ii  mesa-vdpau-drivers:i386                    21.2.2-1ubuntu1                            i386         Mesa VDPAU video acceleration drivers
ii  mesa-vulkan-drivers:amd64                  21.2.2-1ubuntu1                            amd64        Mesa Vulkan graphics drivers
ii  mesa-vulkan-drivers:i386                   21.2.2-1ubuntu1                            i386         Mesa Vulkan graphics drivers
```

**Comment by kkartaltepe** [comment]
Is this still an issue?

**Comment by marceloslacerda** [comment]
I'm traveling so I can't test it right now. You can close it though and if
I get the same error again  I'll open a new issue.

Em sex., 1 de abr. de 2022 às 02:22, Kurt Kartaltepe <
***@***.***> escreveu:

**Comment by kkartaltepe** [comment]
Feel free to update this and we can reopen.
