### ISSUE TITLE
obs crashs on exit in pipewire_capture_unload -> pw_deinit

### ISSUE THREAD

**Issue by jirislaby** [obsproject/obs-studio#5877]
### Operating System Info

Other

### Other OS

openSUSE

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/HYbYvnhMak0vBV5v

### Expected Behavior

No crash.

### Current Behavior

A crash on exit happened.

### Steps to Reproduce

1. start OBS
2. quit OBS

### Anything else we should know?

Stack trace:
```
#0  pw_deinit () at ../src/pipewire/pipewire.c:687
#1  0x00007f13565f699c in free_module (mod=0x5569be2abe40) at /usr/src/debug/obs-studio-27.1.3-1.26.x86_64/libobs/obs-module.c:493
#2  0x00007f13565d934f in obs_shutdown () at /usr/src/debug/obs-studio-27.1.3-1.26.x86_64/libobs/obs.c:1022
#3  0x00005569bbe9f215 in OBSApp::~OBSApp() (this=0x7ffca46e1bb0, __in_chrg=<optimized out>) at /usr/src/debug/obs-studio-27.1.3-1.26.x86_64/UI/obs-app.cpp:1190
#4  0x00005569bbe7c2d4 in run_program (argv=0x7ffca46e2218, argc=<optimized out>, logFile=...) at /usr/src/debug/obs-studio-27.1.3-1.26.x86_64/UI/obs-app.cpp:2149
#5  main(int, char**) (argc=<optimized out>, argv=0x7ffca46e2218) at /usr/src/debug/obs-studio-27.1.3-1.26.x86_64/UI/obs-app.cpp:2825
```
NULL dereference in more detail:
```
#0  pw_deinit () at ../src/pipewire/pipewire.c:687
687                     p->ref++;
(gdb) p p
$4 = (struct plugin *) 0x0
(gdb) l
682             pthread_mutex_lock(&init_lock);
683             pthread_mutex_lock(&support_lock);
684             pw_log_set(NULL);
685             spa_list_consume(p, &registry->plugins, link) {
686                     struct handle *h;
687                     p->ref++;
688                     spa_list_consume(h, &p->handles, link)
689                             unref_handle(h);
690                     unref_plugin(p);
691             }
```

**Comment by kkartaltepe** [comment]
Looks like a bug in pipewire. Based on the most recent commits there it seems they are actively working on issues like this https://github.com/PipeWire/pipewire/commit/b225fe1d54da0fd2e2ab1c9b8db3473a040b4594
