### ISSUE TITLE
Selecting Color for Color Source on Gnome DE Causes Crash

### ISSUE THREAD

**Issue by WillAyd** [obsproject/obs-studio#6287]
### Operating System Info

Other

### Other OS

Manjaro

### OBS Studio Version

27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/avAjFZknC6EF5Z2W

### Expected Behavior

Attempted to pick a color other than the default in the color source should work

### Current Behavior

Application crashes with 
```sh
(process:801233): Gtk-CRITICAL **: 19:39:03.791: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
```

### Steps to Reproduce

1. In the sources pane add a Color Source
2. Click "Select Color"
...

**Comment by kkartaltepe** [comment]
Please provide a backtrace from GDB for the crash.

**Comment by WillAyd** [comment]
Here you go - this is without any debug symbols. Let me know if you need me to recompile with those and happy to do so

<details>

```sh
#0  0x00007fffe2f8b134 in  () at /usr/lib/libgtk-3.so.0
#1  0x00007fffe2faba7c in  () at /usr/lib/libgtk-3.so.0
#2  0x00007fffe2f95965 in  () at /usr/lib/libgtk-3.so.0
#3  0x00007ffff34cb6e3 in g_type_create_instance () at /usr/lib/libgobject-2.0.so.0
#4  0x00007ffff34b2b66 in  () at /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff34b3af5 in g_object_new_with_properties () at /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff34b465a in g_object_new () at /usr/lib/libgobject-2.0.so.0
#7  0x00007fffe31ab7a3 in  () at /usr/lib/libgtk-3.so.0
#8  0x00007ffff34cb6e3 in g_type_create_instance () at /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff34b2b66 in  () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff34b40c3 in g_object_new_valist () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff34b462e in g_object_new () at /usr/lib/libgobject-2.0.so.0
#12 0x00007fffe366635c in QGtk3ColorDialogHelper::QGtk3ColorDialogHelper() ()
    at /usr/lib/qt/plugins/platformthemes/libqgnomeplatformtheme.so
#13 0x00007fffe3668907 in QGnomePlatformTheme::createPlatformDialogHelper(QPlatformTheme::DialogType) const ()
    at /usr/lib/qt/plugins/platformthemes/libqgnomeplatformtheme.so
#14 0x00007ffff5ef4206 in QDialogPrivate::platformHelper() const () at /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff5efa58c in QColorDialog::QColorDialog(QColor const&, QWidget*) () at /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff5efa643 in QColorDialog::QColorDialog(QWidget*) () at /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff5efa6ac in QColorDialog::getColor(QColor const&, QWidget*, QString const&, QFlags<QColorDialog::ColorDialogOption>)
    () at /usr/lib/libQt5Widgets.so.5
#18 0x0000555555619b74 in  ()
#19 0x00005555555df95d in  ()
#20 0x00007ffff500bd24 in  () at /usr/lib/libQt5Core.so.5
#21 0x00007ffff5de1167 in QAbstractButton::clicked(bool) () at /usr/lib/libQt5Widgets.so.5
#22 0x00007ffff5de2fdc in  () at /usr/lib/libQt5Widgets.so.5
--Type <RET> for more, q to quit, c to continue without paging--
#23 0x00007ffff5de67ca in  () at /usr/lib/libQt5Widgets.so.5
#24 0x00007ffff5de6998 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff5d323d6 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#26 0x00007ffff5cfc1c6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#27 0x00007ffff5d00ff7 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#28 0x00007ffff4fdb0aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#29 0x00007ffff5cff9bf in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/libQt5Widgets.so.5
#30 0x00007ffff5d50937 in  () at /usr/lib/libQt5Widgets.so.5
#31 0x00007ffff5d524ec in  () at /usr/lib/libQt5Widgets.so.5
#32 0x00007ffff5cfc1c6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#33 0x00007ffff4fdb0aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#34 0x00007ffff53b0230 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
    at /usr/lib/libQt5Gui.so.5
#35 0x00007ffff539b6e5 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Gui.so.5
#36 0x00007fffe4280f60 in  () at /usr/lib/libQt5XcbQpa.so.5
#37 0x00007ffff33a6ee3 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#38 0x00007ffff33fd0f9 in  () at /usr/lib/libglib-2.0.so.0
#39 0x00007ffff33a4455 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#40 0x00007ffff502708a in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#41 0x00007ffff4fd339b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#42 0x00007ffff4fdead7 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#43 0x00005555555d2bf7 in  ()
#44 0x00007ffff4848310 in __libc_start_call_main () at /usr/lib/libc.so.6
#45 0x00007ffff48483c1 in __libc_start_main_impl () at /usr/lib/libc.so.6
#46 0x00005555555d4025 in  ()
```

</details>

**Comment by WillAyd** [comment]
Nevermind went ahead and compiled from master with Debug flags. Here's a more useful backtrace:

<details>

```sh
#0  0x00007fffe2f27134 in  () at /usr/lib/libgtk-3.so.0
#1  0x00007fffe2f47a7c in  () at /usr/lib/libgtk-3.so.0
#2  0x00007fffe2f31965 in  () at /usr/lib/libgtk-3.so.0
#3  0x00007ffff346d6e3 in g_type_create_instance () at /usr/lib/libgobject-2.0.so.0
#4  0x00007ffff3454b66 in  () at /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff3455af5 in g_object_new_with_properties () at /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff345665a in g_object_new () at /usr/lib/libgobject-2.0.so.0
#7  0x00007fffe31477a3 in  () at /usr/lib/libgtk-3.so.0
#8  0x00007ffff346d6e3 in g_type_create_instance () at /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff3454b66 in  () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff34560c3 in g_object_new_valist () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff345662e in g_object_new () at /usr/lib/libgobject-2.0.so.0
#12 0x00007fffe362a35c in QGtk3ColorDialogHelper::QGtk3ColorDialogHelper() ()
    at /usr/lib/qt/plugins/platformthemes/libqgnomeplatformtheme.so
#13 0x00007fffe362c907 in QGnomePlatformTheme::createPlatformDialogHelper(QPlatformTheme::DialogType) const ()
    at /usr/lib/qt/plugins/platformthemes/libqgnomeplatformtheme.so
#14 0x00007ffff5ec6206 in QDialogPrivate::platformHelper() const () at /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff5ecc58c in QColorDialog::QColorDialog(QColor const&, QWidget*) () at /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff5ecc643 in QColorDialog::QColorDialog(QWidget*) () at /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff5ecc6ac in QColorDialog::getColor(QColor const&, QWidget*, QString const&, QFlags<QColorDialog::ColorDialogOption>)
    () at /usr/lib/libQt5Widgets.so.5
#18 0x000055555562ab80 in ColorSourceToolbar::on_choose_clicked() (this=0x5555586da990)
    at /home/willayd/clones/obs-studio/UI/context-bar-controls.cpp:553
#19 0x00005555555c2726 in ColorSourceToolbar::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)
    (_o=0x5555586da990, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fffffffc730)
    at /home/willayd/clones/obs-studio/build/UI/obs_autogen/EWIEGA46WW/moc_context-bar-controls.cpp:855
#20 0x00005555555c2822 in ColorSourceToolbar::qt_metacall(QMetaObject::Call, int, void**)
    (this=0x5555586da990, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fffffffc730)
    at /home/willayd/clones/obs-studio/build/UI/obs_autogen/EWIEGA46WW/moc_context-bar-controls.cpp:892
#21 0x00007ffff4fafd24 in  () at /usr/lib/libQt5Core.so.5
#22 0x00007ffff5db3167 in QAbstractButton::clicked(bool) () at /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff5db4fdc in  () at /usr/lib/libQt5Widgets.so.5
#24 0x00007ffff5db87ca in  () at /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff5db8998 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#26 0x00007ffff5d043d6 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#27 0x00007ffff5cce1c6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#28 0x00007ffff5cd2ff7 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#29 0x00005555555e3a6e in OBSApp::notify(QObject*, QEvent*) (this=0x7fffffffd5b0, receiver=0x55555873dc00, e=0x7fffffffcd10)
    at /home/willayd/clones/obs-studio/UI/obs-app.cpp:1617
#30 0x00007ffff4f7f0aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#31 0x00007ffff5cd19bf in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/libQt5Widgets.so.5
#32 0x00007ffff5d22937 in  () at /usr/lib/libQt5Widgets.so.5
#33 0x00007ffff5d244ec in  () at /usr/lib/libQt5Widgets.so.5
#34 0x00007ffff5cce1c6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#35 0x00005555555e3a6e in OBSApp::notify(QObject*, QEvent*) (this=0x7fffffffd5b0, receiver=0x555555d31720, e=0x7fffffffd0e0)
    at /home/willayd/clones/obs-studio/UI/obs-app.cpp:1617
#36 0x00007ffff4f7f0aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#37 0x00007ffff5352230 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
    at /usr/lib/libQt5Gui.so.5
#38 0x00007ffff533d6e5 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Gui.so.5
#39 0x00007fffe41dbf60 in  () at /usr/lib/libQt5XcbQpa.so.5
#40 0x00007ffff334aee3 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#41 0x00007ffff33a10f9 in  () at /usr/lib/libglib-2.0.so.0
#42 0x00007ffff3348455 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#43 0x00007ffff4fcb08a in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#44 0x00007ffff4f7739b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#45 0x00007ffff4f82ad7 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#46 0x00005555555e63a9 in run_program(std::fstream&, int, char**) (logFile=..., argc=1, argv=0x7fffffffdd68)
    at /home/willayd/clones/obs-studio/UI/obs-app.cpp:2211
#47 0x00005555555e885d in main(int, char**) (argc=1, argv=0x7fffffffdd68) at /home/willayd/clones/obs-studio/UI/obs-app.cpp:2907
```

</details>

**Comment by kkartaltepe** [comment]
This looks like a bug in your system packages.

**Comment by WillAyd** [comment]
Yea looking at it now I don't think its an OBS thing. Actually this solution fixed things for me:

**https://forum.manjaro.org/t/qt5ct-crash-after-trying-to-change-the-font-in-gnome/81957/12**

Thanks for the guidance and maintaining such a great tool
