### ISSUE TITLE
SIGSEGV on Startup With libva 2.15.0

### ISSUE THREAD

**Issue by ewhac** [obsproject/obs-studio#7012]
### Operating System Info

Other

### Other OS

Debian Bookworm/Sid

### OBS Studio Version

28.0.0-beta1

### OBS Studio Log URL

See GDB session below

### Expected Behavior

Program launches and runs.

### Current Behavior

With libva 2.15.0 installed, the program crashes with segfault during startup.  UI does not appear.  (This behavior also happens in OBS 27.x.)

However, if I downgrade libva to 2.14.0, then the program runs fine.

GDB session:

```
ewhac@exiguous:~/hackery/obs-studio/build$ gdb obs
GNU gdb (Debian 12.1-3) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from obs...
(No debugging symbols found in obs)
(gdb) run
Starting program: /usr/local/bin/obs 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe81ff640 (LWP 14505)]
[New Thread 0x7fffe796a640 (LWP 14506)]
[New Thread 0x7fffe7169640 (LWP 14507)]
debug: Found portal inhibitor
[New Thread 0x7fffe61be640 (LWP 14508)]
[New Thread 0x7fffe59bd640 (LWP 14509)]
[New Thread 0x7fffe51bc640 (LWP 14510)]
[New Thread 0x7fffe49bb640 (LWP 14511)]
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/local/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/local/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Yami.qss
Attempted path: /usr/local/share/obs/obs-studio/themes/Yami.qss
info: Using EGL/X11
info: CPU Name: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
info: CPU Speed: 2984.439MHz
info: Physical Cores: 6, Logical Cores: 12
info: Physical Memory: 15917MB Total, 6757MB Free
info: Kernel Version: Linux 5.18.0-3-amd64
info: Distribution: "Debian GNU/Linux" Unknown
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
[New Thread 0x7fffc7fff640 (LWP 14512)]
[New Thread 0x7fffc77fe640 (LWP 14513)]
info: Qt Version: 5.15.4 (runtime), 5.15.4 (compiled)
info: Portable mode: false
[New Thread 0x7fffc6ffd640 (LWP 14514)]
qt.svg: Cannot open file '/usr/local/share/obs/obs-studio/themes/Dark/Close.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/local/share/obs/obs-studio/themes/Dark/Close.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/local/share/obs/obs-studio/themes/Dark/Popout.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/local/share/obs/obs-studio/themes/Dark/Popout.svg', because: No such file or directory
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/local/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 28.0.0-beta1-55-g7f3ea4e00 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
	max buffering:   960 milliseconds
	buffering type:  dynamically increasing
[New Thread 0x7fffc67fc640 (LWP 14515)]
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 470.141.03, shading language 3.30 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1920x1080
	downscale filter:  Bicubic
	fps:               30/1
	format:            I444
	YUV mode:          Rec. 709/Full
[New Thread 0x7fffc516e640 (LWP 14516)]
info: NV12 texture support not available
info: P010 texture support not available
[New Thread 0x7fffaa24e640 (LWP 14517)]
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
[New Thread 0x7fffa974a640 (LWP 14518)]
info: [pipewire] No captures available
[Detaching after vfork from child process 14519]
info: NVENC supported
info: FFMPEG VAAPI supported
info: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.0.1 | RPC Version: 1)
info: [obs-websocket] [obs_module_load] Qt version (compile-time): 5.15.4 | Qt version (run-time): 5.15.4
info: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201
info: [obs-websocket] [obs_module_load] Module loaded.
[New Thread 0x7fff9bfff640 (LWP 14521)]
[New Thread 0x7fff9b7fe640 (LWP 14522)]
[Thread 0x7fff9b7fe640 (LWP 14522) exited]
info: [vlc-video]: VLC 3.0.17.4 Vetinari found, VLC video source enabled
info: [Move Transition] loaded version 2.4.3
info: [obs-websocket] you can haz websockets (version 4.9.1)
info: [obs-websocket] qt version (compile-time): 5.15.2 ; qt version (run-time): 5.15.4
[Thread 0x7fff9bfff640 (LWP 14521) exited]
info: [obs-websocket] module loaded!
info: ---------------------------------
info:   Loaded Modules:
info:     obs-websocket.so
info:     move-transition.so
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-vst.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-pipewire.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-output-ui.so
info:     decklink-captions.so
info: ---------------------------------
info: ==== Startup complete ===============================================
qt.svg: Cannot open file '/usr/local/share/obs/obs-studio/themes/Dark/Close.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/local/share/obs/obs-studio/themes/Dark/Close.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/local/share/obs/obs-studio/themes/Dark/Popout.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/local/share/obs/obs-studio/themes/Dark/Popout.svg', because: No such file or directory
info: All scene data cleared
info: ------------------------------------------------
info: [obs-scripting]: Loaded lua script: countdown.lua
info: [obs-scripting]: Loaded lua script: instant-replay.lua
info: v4l2-input: Start capture from /dev/video0
info: v4l2-input: Input: 0
info: v4l2-input: Resolution: 1280x720
info: v4l2-input: Pixelformat: YUYV
info: v4l2-input: Linesize: 2560 Bytes
info: v4l2-input: Framerate: 7.50 fps
[New Thread 0x7fff9b7fe640 (LWP 14523)]
info: v4l2-input: /dev/video0: select timeout set to 666666 (5x frame periods)
[New Thread 0x7fff9a0f5640 (LWP 14524)]
[New Thread 0x7fff998f4640 (LWP 14525)]
info: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.56) 15.0.0'
error: pulse-input: An error occurred while getting the source info!
info: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.56) 15.0.0'
info: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_00_1b.0.analog-stereo.monitor'
info: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.56) 15.0.0'
error: pulse-input: An error occurred while getting the source info!
info: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.56) 15.0.0'
error: pulse-input: An error occurred while getting the source info!
info: [window-capture: 'neovide'] update settings:
	title: unknown
	class: unknown

info: v4l2-input: Start capture from /dev/video0
error: v4l2-input: Unable to set input 0
error: v4l2-input: Initialization failed, errno: Device or resource busy
[New Thread 0x7fff990f3640 (LWP 14526)]
info: [Media Source 'MED: ewhac Special Presentation']: settings:
	input:                   /home/ewhac/synfig/full_logo.mp4
	input_format:            (null)
	speed:                   100
	is_looping:              no
	is_linear_alpha:         no
	is_hw_decoding:          yes
	is_clear_on_media_end:   yes
	restart_on_activate:     yes
	close_when_inactive:     no
	ffmpeg_options:          
info: Set FFmpeg options: 
info: xshm-input: Geometry 3440x1440 @ 0,0
info: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.56) 15.0.0'
info: pulse-input: Audio format: s16le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_input.usb-SunplusIT_Inc_UC70_7UC20210413V02-02.analog-stereo'

Thread 21 "mp_media_thread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff990f3640 (LWP 14526)]
0x00007fffee8f0080 in XDisplayString () from /usr/lib/x86_64-linux-gnu/libX11.so.6
(gdb) bt
#0  0x00007fffee8f0080 in XDisplayString () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#1  0x00007fff98605ee5 in __vaDriverInit_1_0 () at /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
#2  0x00007ffff1c60e3c in  () at /usr/lib/x86_64-linux-gnu/libva.so.2
#3  0x00007ffff1c61fb6 in vaInitialize () at /usr/lib/x86_64-linux-gnu/libva.so.2
#4  0x00007ffff6851c7a in  () at /usr/lib/x86_64-linux-gnu/libavutil.so.57
#5  0x00007ffff684520d in av_hwdevice_ctx_create () at /usr/lib/x86_64-linux-gnu/libavutil.so.57
#6  0x00007fffa89118c9 in mp_decode_init () at /usr/local//lib/obs-plugins/obs-ffmpeg.so
#7  0x00007fffa8910940 in  () at /usr/local//lib/obs-plugins/obs-ffmpeg.so
#8  0x00007ffff3e87b27 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:435
#9  0x00007ffff3f0a78c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

### Steps to Reproduce

1. Buidl and install OBS Studio 28.0.0-beta1 on a system with libva 2.15.0.  (Shouldn't matter, but my build disables `OBS_BROWSER`.)
2. Launch it.

Program almost immediately segfaults.

### Anything else we should know?

Using `nvidia-driver` version 470.141.03-1

**Comment by kkartaltepe** [comment]
> With libva 2.15.0 installed, the program crashes with segfault during startup. UI does not appear. (This behavior also happens in OBS 27.x.)
> 
> However, if I downgrade libva to 2.14.0, then the program runs fine.

Sounds like this is not our bug and you should it report it to libva where you identified the regression. Also you are using nvidia proprietary drivers but appear to have installed mesa drivers as well which is not a very supported configuration.

**Comment by ewhac** [comment]
> Also you are using nvidia proprietary drivers but appear to have installed mesa drivers as well which is not a very supported configuration.

Uh, no, this is quite common thanks to GLVND, and they can happily live side by side.

I'll file a bug with libva, but I'm not sanquine about the results.
