### ISSUE TITLE
[28.0.0-beta2 crash] OBS crashes when hiding audio mixer item

### ISSUE THREAD

**Issue by cg2121** [obsproject/obs-studio#7031]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/bEONzsxvokDplqO_

### Expected Behavior

Don't crash

### Current Behavior

Crashes when hiding mixer item

It only happens on Linux, as I tested it on Windows and nothing happens. Seems to me like a QT bug with the version installed on Ubuntu 22.04, which is 6.2.4, as it is crashing in that code.

### Steps to Reproduce

1. Open OBS
2. Hide item in audio mixer, sometimes it takes multiple times, most of time just once
3. Notice OBS crashes
...

### Anything else we should know?

GDB backtrace:

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737139753920)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737139753920)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737139753920, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007ffff427f476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007ffff42657f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff42c66f6 in __libc_message
    (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff4418b8c "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007ffff42ddd7c in malloc_printerr
    (str=str@entry=0x7ffff4416711 "corrupted size vs. prev_size")
    at ./malloc/malloc.c:5664
#7  0x00007ffff42de862 in unlink_chunk
    (p=<optimized out>, av=0x7ffff4456c80 <main_arena>)
    at ./malloc/malloc.c:1629
#8  0x00007ffff42de9e9 in malloc_consolidate
    (av=av@entry=0x7ffff4456c80 <main_arena>) at ./malloc/malloc.c:4780
#9  0x00007ffff42dff20 in _int_free
    (av=0x7ffff4456c80 <main_arena>, p=0x5555570a55f0, have_lock=<optimized out>) at ./malloc/malloc.c:4674
#10 0x00007ffff42e24d3 in __GI___libc_free (mem=<optimized out>)
    at ./malloc/malloc.c:3391
#11 0x00007ffff500b7a6 in  () at /lib/x86_64-linux-gnu/libQt6Gui.so.6
#12 0x00007ffff50056a1 in  () at /lib/x86_64-linux-gnu/libQt6Gui.so.6
#13 0x00007ffff500587d in  () at /lib/x86_64-linux-gnu/libQt6Gui.so.6
#14 0x00007ffff5005d1d in QRasterPaintEngine::~QRasterPaintEngine() ()
    at /lib/x86_64-linux-gnu/libQt6Gui.so.6
#15 0x00007ffff4edccab in QImageData::~QImageData() ()
    at /lib/x86_64-linux-gnu/libQt6Gui.so.6
#16 0x00007ffff4edcdbc in QImage::~QImage() ()
    at /lib/x86_64-linux-gnu/libQt6Gui.so.6
#17 0x00007fffead96695 in  ()
    at /usr/lib/x86_64-linux-gnu/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6
#18 0x00007fffead9675b in  ()
    at /usr/lib/x86_64-linux-gnu/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6
#19 0x00007fffead9682d in  ()
    at /usr/lib/x86_64-linux-gnu/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6
#20 0x00007ffff4f93d8f in QBackingStore::~QBackingStore() ()
    at /lib/x86_64-linux-gnu/libQt6Gui.so.6
#21 0x00007ffff5a17ae3 in QWidgetPrivate::deleteTLSysExtra() ()
    at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#22 0x00007ffff5a26b38 in QWidget::destroy(bool, bool) ()
    at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#23 0x00007ffff5a2d7dd in QWidget::~QWidget() ()
    at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#24 0x00005555556d7668 in OBSBasic::VolControlContextMenu()
    (this=<optimized out>)
    at /home/clayton/obs-studio/UI/window-basic-main.cpp:3513
#25 0x00007ffff498d483 in  () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#26 0x00007ffff498d483 in  () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#27 0x00007ffff5b06cb6 in QAbstractButton::clicked(bool) ()
    at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#28 0x00007ffff5b06f4e in  () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#29 0x00007ffff5b08694 in  () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#30 0x00007ffff5b088c3 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
    at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#31 0x00007ffff5a320e8 in QWidget::event(QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#32 0x00007ffff59d8d36 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#33 0x00007ffff59e22d7 in QApplication::notify(QObject*, QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#34 0x00007ffff4934eb8 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#35 0x00007ffff59e0de2 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
    at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#36 0x00007ffff5a4480b in  () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#37 0x00007ffff5a47635 in  () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#38 0x00007ffff59d8d36 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#39 0x00007ffff4934eb8 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#40 0x00007ffff4f396bf in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt6Gui.so.6
#41 0x00007ffff4f81c8c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt6Gui.so.6
#42 0x00007fffeadbe86e in  ()
    at /usr/lib/x86_64-linux-gnu/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6
#43 0x00007ffff26dcd1b in g_main_context_dispatch ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#44 0x00007ffff27316f8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#45 0x00007ffff26da3c3 in g_main_context_iteration ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#46 0x00007ffff4b5d30e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop:
:ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#47 0x00007ffff4941f3b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#48 0x00007ffff493d553 in QCoreApplication::exec() ()
    at /lib/x86_64-linux-gnu/libQt6Core.so.6
#49 0x00005555555ec754 in run_program
    (argv=0x7fffffffe0e8, argc=<optimized out>, logFile=...)
    at /home/clayton/obs-studio/UI/obs-app.cpp:2340
#50 main(int, char**) (argc=<optimized out>, argv=0x7fffffffe0e8)
    at /home/clayton/obs-studio/UI/obs-app.cpp:3050
```

**Comment by kkartaltepe** [comment]
fwiw i couldnt trigger this against a qt5 build
