### ISSUE TITLE
Linux (KDE Neon) version will not open.

### ISSUE THREAD

**Issue by Jazztache** [obsproject/obs-studio#7285]
### Operating System Info

Other

### Other OS

Linux KDE Neon 5.25 (Based on Ubuntu 22.04)

### OBS Studio Version

Git

### OBS Studio Log URL

See 'Current Behaviour'. It contains the --verbose log in full. Unable to access Help menu if initial build doesn't work.

### Expected Behavior

After compiling the Git build of OBS, and following the Ubuntu instructions (as is standard for KDE Neon users) I expected to ahev the newest version of OBS up and running. This also includes Virtual Camera, which is a feature I really need.

### Current Behavior

When I ran OBS from the terminal, I was greeted by a SIGSEV Error. I also tried opening my OBS shortcut in my task manager, and it wouldn't open. I then attempted to open OBS via the terminal in verbose mode so I could get more granular error reporting. This is what was shown.

```debug: Found portal inhibitor
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/locale/en-GB.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-GB.ini
info: Using preferred locale 'en-GB'
Attempted path: share/obs/obs-studio/themes/Yami.qss
Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Command Line Arguments: --verbose
info: Using EGL/X11
info: CPU Name: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
info: CPU Speed: 3800.000MHz
info: Physical Cores: 8, Logical Cores: 16
info: Physical Memory: 15918MB Total, 3356MB Free
info: Kernel Version: Linux 5.15.0-46-generic
info: Distribution: "KDE neon" "20.04"
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.13
debug: found alternate keycode 62 for OBS_KEY_SHIFT which already has keycode 50
debug: found alternate keycode 105 for OBS_KEY_CONTROL which already has keycode 37
debug: found alternate keycode 108 for OBS_KEY_ALT which already has keycode 64
debug: found alternate keycode 129 for OBS_KEY_NUMPERIOD which already has keycode 91
debug: found alternate keycode 190 for OBS_KEY_REDO which already has keycode 137
debug: found alternate keycode 218 for OBS_KEY_PRINT which already has keycode 107
debug: found alternate keycode 231 for OBS_KEY_CANCEL which already has keycode 136
info: Qt Version: 5.15.5 (runtime), 5.12.8 (compiled)
info: Portable mode: false
qt.svg: Cannot open file '/usr/share/obs/obs-studio/themes/Dark/Close.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/share/obs/obs-studio/themes/Dark/Close.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/share/obs/obs-studio/themes/Dark/Popout.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/share/obs/obs-studio/themes/Dark/Popout.svg', because: No such file or directory
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 28.0.1 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
        samples per sec: 48000
        speakers:        2
        max buffering:   960 milliseconds
        buffering type:  dynamically increasing
info: ---------------------------------
info: Initializing OpenGL...
debug: Created EGLDisplay 0x55af5b53f690
info: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce RTX 2060/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 510.85.02, shading language 3.30 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
        base resolution:   1920x1080
        output resolution: 1920x1080
        downscale filter:  Bicubic
        fps:               60/1
        format:            NV12
        YUV mode:          Rec. 709/Partial
info: NV12 texture support not available
info: P010 texture support not available
info: Audio monitoring device:
        name: Default
        id: default
info: ---------------------------------
debug: ---------------------------------
error: os_dlopen(/usr//lib/x86_64-linux-gnu/obs-plugins/aja-output-ui.so->/usr//lib/x86_64-linux-gnu/obs-plugins/aja-output-ui.so): /usr//lib/x86_64-linux-gnu/obs-plugins/aja-output-ui.so: undefined symbol: __libc_single_threaded

warning: Module '/usr//lib/x86_64-linux-gnu/obs-plugins/aja-output-ui.so' not loaded
debug: Failed to load module file '/usr//lib/x86_64-linux-gnu/obs-plugins/aja-output-ui.so', file not found
debug: ---------------------------------
error: os_dlopen(/usr//lib/x86_64-linux-gnu/obs-plugins/aja.so->/usr//lib/x86_64-linux-gnu/obs-plugins/aja.so): /usr//lib/x86_64-linux-gnu/obs-plugins/aja.so: undefined symbol: __libc_single_threaded

warning: Module '/usr//lib/x86_64-linux-gnu/obs-plugins/aja.so' not loaded
debug: Failed to load module file '/usr//lib/x86_64-linux-gnu/obs-plugins/aja.so', file not found
debug: ---------------------------------
debug: Loading module: decklink-captions.so
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
debug: ---------------------------------
debug: Loading module: decklink-output-ui.so
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
debug: ---------------------------------
debug: Loading module: decklink.so
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
debug: ---------------------------------
debug: Loading module: frontend-tools.so
warning: Failed to load 'en-GB' text for module: 'frontend-tools.so'
debug: ---------------------------------
debug: Loading module: image-source.so
debug: ---------------------------------
debug: Required module function 'obs_module_load' in module '/usr//lib/x86_64-linux-gnu/obs-plugins/libcef.so' not found, loading of module failed
debug: Failed to load module file '/usr//lib/x86_64-linux-gnu/obs-plugins/libcef.so', not an OBS plugin
debug: ---------------------------------
debug: Required module function 'obs_module_load' in module '/usr//lib/x86_64-linux-gnu/obs-plugins/libEGL.so' not found, loading of module failed
debug: Failed to load module file '/usr//lib/x86_64-linux-gnu/obs-plugins/libEGL.so', not an OBS plugin
debug: ---------------------------------
debug: Required module function 'obs_module_load' in module '/usr//lib/x86_64-linux-gnu/obs-plugins/libGLESv2.so' not found, loading of module failed
debug: Failed to load module file '/usr//lib/x86_64-linux-gnu/obs-plugins/libGLESv2.so', not an OBS plugin
debug: ---------------------------------
debug: Required module function 'obs_module_load' in module '/usr//lib/x86_64-linux-gnu/obs-plugins/libvk_swiftshader.so' not found, loading of module failed
debug: Failed to load module file '/usr//lib/x86_64-linux-gnu/obs-plugins/libvk_swiftshader.so', not an OBS plugin
debug: ---------------------------------
debug: Loading module: linux-alsa.so
warning: Failed to load 'en-GB' text for module: 'linux-alsa.so'
debug: ---------------------------------
debug: Loading module: linux-capture.so
warning: Failed to load 'en-GB' text for module: 'linux-capture.so'
debug: ---------------------------------
debug: Loading module: linux-jack.so
warning: Failed to load 'en-GB' text for module: 'linux-jack.so'
debug: ---------------------------------
debug: Loading module: linux-pulseaudio.so
warning: Failed to load 'en-GB' text for module: 'linux-pulseaudio.so'
debug: ---------------------------------
debug: Loading module: linux-v4l2.so
debug: ---------------------------------
debug: Loading module: obs-browser.so
info: [obs-browser]: Version 2.18.5
info: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures_143.2591+g4204d54+chromium-103.0.5060.134 (compiled)
debug: ---------------------------------
debug: Loading module: obs-ffmpeg.so
info: NVENC supported
info: FFMPEG VAAPI supported
debug: ---------------------------------
debug: Loading module: obs-filters.so
debug: ---------------------------------
debug: Loading module: obs-libfdk.so
warning: Failed to load 'en-GB' text for module: 'obs-libfdk.so'
debug: ---------------------------------
debug: Loading module: obs-outputs.so
debug: ---------------------------------
debug: Loading module: obs-transitions.so
debug: ---------------------------------
debug: Loading module: obs-vst.so
warning: Failed to load 'en-GB' text for module: 'obs-vst.so'
debug: ---------------------------------
debug: Loading module: obs-websocket.so
warning: Failed to load 'en-GB' text for module: 'obs-websocket.so'
info: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.0.1 | RPC Version: 1)
info: [obs-websocket] [obs_module_load] Qt version (compile-time): 5.12.8 | Qt version (run-time): 5.15.5
info: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201
info: [obs-websocket] [obs_module_load] Module loaded.
debug: ---------------------------------
debug: Loading module: obs-x264.so
warning: Failed to load 'en-GB' text for module: 'obs-x264.so'
debug: ---------------------------------
debug: Loading module: rtmp-services.so
warning: Failed to load 'en-GB' text for module: 'rtmp-services.so'
debug: ---------------------------------
debug: Loading module: text-freetype2.so
debug: ---------------------------------
debug: Loading module: vlc-video.so
info: [vlc-video]: VLC 3.0.9.2 Vetinari found, VLC video source enabled
debug: ---------------------------------
debug: Loading module: nvfbc.so
fish: “obs --verbose” terminated by signal SIGSEGV (Address boundary error)
jazztache@jazztache-neon ~ [SIGSEGV]> 
```

### Steps to Reproduce

1. Compile OBS using the instructions. https://github.com/obsproject/obs-studio/wiki/Install-Instructions . On Neon, Qt6 is unavailable (apt failure), so try Qt5.
2. Open OBS via Command Line to see if it opens. It doesn't.
3. If that fails, attempt to open via shortcut. Still doesn't open.
4. Debug via command line using --verbose; it still fails to open.
5. Sit in defeat and report to devs :)

### Anything else we should know?

I feel as if the modules not loading this.
Here is a GNU Debugger backtrace. The backtrace methods and the --verbose output seem to support this.
```Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
0x00007ffff02f94e4 in XInternAtom () from /lib/x86_64-linux-gnu/libX11.so.6
(gdb) backtrace
#0  0x00007ffff02f94e4 in XInternAtom () at /lib/x86_64-linux-gnu/libX11.so.6
#1  0x00007fffa0be1fd4 in obs_module_load () at ../nvfbc.c:1109
#2  0x00007ffff56a42bb in obs_init_module () at /usr/lib/x86_64-linux-gnu/libobs.so.0
#3  0x00007ffff56a5875 in  () at /usr/lib/x86_64-linux-gnu/libobs.so.0
#4  0x00007ffff56a4d78 in obs_find_modules2 () at /usr/lib/x86_64-linux-gnu/libobs.so.0
#5  0x00007ffff56a5557 in obs_load_all_modules2 () at /usr/lib/x86_64-linux-gnu/libobs.so.0
#6  0x00005555556d42bd in  ()
#7  0x00005555556120ec in  ()
#8  0x00005555555f146a in main ()
(gdb) 
```

**Comment by tytan652** [comment]
NvFBC no longer works since OBS 28. A newer version was made to avoid crashes with EGL but NvFBC does not work with EGL.

**Comment by Jazztache** [comment]
Ok, where can I get this newer version/alternative of NvFBC? Is it something to do with my config files?
