### ISSUE TITLE
Crash when a browser source tries to open a file dialog (CEF / libcef related)

### ISSUE THREAD

**Issue by Refragg** [obsproject/obs-studio#8012]
### Operating System Info

Ubuntu 22.10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/cH62lhxBDeI6Q5al

### OBS Studio Crash Log URL

https://obsproject.com/logs/IZXyFneFQt6fu8Rp

### Expected Behavior

The file dialog should successfully open without crashing the program

### Current Behavior

OBS crashes with a segfault in libcef.so when a browser source tries to open a file dialog.

### Steps to Reproduce

1. Open OBS
2. Add a new "Browser" source to the scene
3. Change the link to a page containing a file dialog interaction (i.e.: https://obsproject.com/tools/analyzer#logFile)
4. Right click on the source and click Interact
5. Trigger the file dialog on the website
6. Observe the crash

### Anything else we should know?

[Here is a link](https://discord.com/channels/348973006581923840/636682839382949888/1060601476231221268) to the related discussion in the OBS Community Discord server.

Here is the gdb output: (except the libcef shipped doesn't have debug symbols so this is probably not the most useful)

```
Starting program: /usr/bin/obs 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe9d8f6c0 (LWP 12997)]
[New Thread 0x7fffe88a26c0 (LWP 12998)]
[New Thread 0x7fffe3fff6c0 (LWP 12999)]
[New Thread 0x7fffe37fe6c0 (LWP 13000)]
[New Thread 0x7fffe2e456c0 (LWP 13001)]
[New Thread 0x7fffe24cf6c0 (LWP 13002)]
[New Thread 0x7fffe1cce6c0 (LWP 13003)]
[New Thread 0x7fffe14bd6c0 (LWP 13004)]
[New Thread 0x7fffe0a966c0 (LWP 13005)]
[New Thread 0x7fffc65ff6c0 (LWP 13006)]
[New Thread 0x7fffc5dfe6c0 (LWP 13007)]
[New Thread 0x7fffc55fd6c0 (LWP 13008)]
[New Thread 0x7fffc49fc6c0 (LWP 13009)]
[New Thread 0x7fffb8dff6c0 (LWP 13010)]
[New Thread 0x7fffa3fff6c0 (LWP 13011)]
[New Thread 0x7fffa37fe6c0 (LWP 13012)]
[New Thread 0x7fffa2ffd6c0 (LWP 13013)]
[New Thread 0x7fffa27fc6c0 (LWP 13014)]
[New Thread 0x7fffa0e2b6c0 (LWP 13015)]
[Detaching after fork from child process 13016]
[Detaching after fork from child process 13017]
[Detaching after fork from child process 13018]
[Detaching after fork from child process 13019]
[Detaching after fork from child process 13020]
[Detaching after fork from child process 13021]
[New Thread 0x7fff87bff6c0 (LWP 13022)]
[Detaching after fork from child process 13023]
[Detaching after fork from child process 13024]
[Detaching after fork from child process 13025]
[Detaching after fork from child process 13026]
[Detaching after fork from child process 13027]
[Detaching after fork from child process 13028]
[Detaching after fork from child process 13029]
[Detaching after fork from child process 13030]
[Detaching after fork from child process 13031]
[Detaching after fork from child process 13032]
[Detaching after fork from child process 13033]
[Detaching after vfork from child process 13034]
[Detaching after fork from child process 13036]
[Detaching after fork from child process 13037]
[Detaching after fork from child process 13038]
[Detaching after fork from child process 13039]
[Detaching after fork from child process 13040]
[Detaching after fork from child process 13041]
[Detaching after fork from child process 13042]
[Detaching after fork from child process 13043]
[Detaching after fork from child process 13044]
[Detaching after fork from child process 13045]
[New Thread 0x7fff7199b6c0 (LWP 13046)]
[New Thread 0x7fff7119a6c0 (LWP 13047)]
[Detaching after fork from child process 13048]
[Thread 0x7fff7119a6c0 (LWP 13047) exited]
[Detaching after fork from child process 13049]
[New Thread 0x7fff7119a6c0 (LWP 13050)]
[New Thread 0x7fff709996c0 (LWP 13051)]
[New Thread 0x7fff5edff6c0 (LWP 13052)]
[Detaching after fork from child process 13053]
[Detaching after fork from child process 13054]
[New Thread 0x7fff5e5fe6c0 (LWP 13055)]
[New Thread 0x7fff57fff6c0 (LWP 13056)]
[New Thread 0x7fff577fe6c0 (LWP 13057)]
[New Thread 0x7fff56ffd6c0 (LWP 13058)]
[New Thread 0x7fff567fc6c0 (LWP 13059)]
[New Thread 0x7fff55ffb6c0 (LWP 13060)]
[New Thread 0x7fff557fa6c0 (LWP 13061)]
[New Thread 0x7fff548106c0 (LWP 13062)]
[New Thread 0x7fff3f7fe6c0 (LWP 13064)]
[New Thread 0x7fff3ffff6c0 (LWP 13063)]
[New Thread 0x7fff3effd6c0 (LWP 13065)]
[New Thread 0x7fff3e7fc6c0 (LWP 13066)]
[New Thread 0x7fff3dffb6c0 (LWP 13068)]
[New Thread 0x7fff3d7fa6c0 (LWP 13070)]
[Detaching after fork from child process 13076]
[New Thread 0x7fff1702c6c0 (LWP 13121)]
[New Thread 0x7fff1682b6c0 (LWP 13122)]
[Thread 0x7fff7199b6c0 (LWP 13046) exited]
[New Thread 0x7fff1602a6c0 (LWP 13200)]
[New Thread 0x7fff158296c0 (LWP 13203)]
[New Thread 0x7fff148276c0 (LWP 13205)]
[New Thread 0x7fff150286c0 (LWP 13204)]
[New Thread 0x7fff07f466c0 (LWP 13225)]
[Thread 0x7fff07f466c0 (LWP 13225) exited]
[Thread 0x7fff148276c0 (LWP 13205) exited]

Thread 25 "CrBrowserMain" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff709996c0 (LWP 13051)]
0x00007fff79589324 in ?? () from /usr//lib/x86_64-linux-gnu/obs-plugins/libcef.so
#0  0x00007fff79589324 in ?? () from /usr//lib/x86_64-linux-gnu/obs-plugins/libcef.so
No symbol table info available.
#1  0xaaaaaaaa00000000 in ?? ()
No symbol table info available.
#2  0x0000000000000000 in ?? ()
No symbol table info available.
```

This issue has been reproduced by a friend on Linux Mint Cinnamon 21.1 with the same OBS version

I have attempted to use both the Flatpak, the prebuilt binary from the PPA and building the program from source code, all of these lead to the same crash. The version in my distro's repos (https://packages.ubuntu.com/kinetic/video/obs-studio) does not contain the obs-browser plugin therefore, the crash is not reproducible there

I can reproduce this crash on the **OBS 29.0 Beta 2** version aswell.

**Comment by kkartaltepe** [comment]
I cannot replicate this, on both x11 and wayland it appears file selection is disabled.

**Comment by kkartaltepe** [comment]
Also looks like its already tracked in the correct place over at https://github.com/obsproject/obs-browser/issues/384
