### ISSUE TITLE
Crash when add media source with srt or udp url

### ISSUE THREAD

**Issue by ogmkp** [obsproject/obs-studio#8386]
### Operating System Info

Other

### Other OS

Debian 11 Bullseye

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/KfNeZ5QLoL659Zrl

### Expected Behavior

No segfault with media source

### Current Behavior

Crash on segfault when add a srt or udp in studio mode
Reproduced on OBS 27.2.4

### Steps to Reproduce

1. Put OBS in studio mode
2. Add media source
3.  Uncheck local file and add udp://:5050 on url
4. Press OK
5. Immediatly delete this media source
6. Crash
...

### Anything else we should know?

gdb back trace

```
[Thread 0x7fff24d3b700 (LWP 90412) exited]
info: Switched to Preview/Program mode
info: ------------------------------------------------
info: [Media Source 'Source média']: settings:
	input:                   
	input_format:            (null)
	speed:                   100
	is_looping:              no
	is_linear_alpha:         no
	is_hw_decoding:          no
	is_clear_on_media_end:   yes
	restart_on_activate:     yes
	close_when_inactive:     no
	ffmpeg_options:          
info: User added source 'Source média' (ffmpeg_source) to scene 'Scène'
[New Thread 0x7fff24d3b700 (LWP 90454)]
info: [Media Source 'Source média']: settings:
	input:                   udp://:5050
	input_format:            
	speed:                   100
	is_looping:              no
	is_linear_alpha:         no
	is_hw_decoding:          no
	is_clear_on_media_end:   yes
	restart_on_activate:     yes
	close_when_inactive:     no
	ffmpeg_options:          
info: Set FFmpeg options: 
[udp @ 0x7fff98001b40] attempted to set receive buffer to size 2097152 but it only ended up set as 425984
[New Thread 0x7fff2553c700 (LWP 90455)]
info: User Removed source 'Source média' (ffmpeg_source) from scene 'Scène'
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 15419, resource id: 13542419, major code: 40 (TranslateCoords), minor code: 0
--Type <RET> for more, q to quit, c to continue without paging--q
Quit
(gdb) tr
No default breakpoint address now.
(gdb) bt
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x7fffffffd028) at ../sysdeps/nptl/futex-internal.h:186
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5555559d3018, cond=0x7fffffffd000) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7fffffffd000, mutex=0x5555559d3018) at pthread_cond_wait.c:638
#3  0x00007fffef3f5edf in  () at /lib/x86_64-linux-gnu/libxcb.so.1
#4  0x00007fffef3f7d7f in  () at /lib/x86_64-linux-gnu/libxcb.so.1
#5  0x00007fffef3f7e91 in xcb_wait_for_reply () at /lib/x86_64-linux-gnu/libxcb.so.1
#6  0x00007fffeb32beaa in QXcbConnection::sync() () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#7  0x00007fffeb342ea3 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#8  0x00007fffeb3432c0 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#9  0x00007ffff50edabe in QBackingStore::beginPaint(QRegion const&) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#10 0x00007ffff590b6a2 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff593b6d7 in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff58fb15f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff4b52fca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff4b55a01 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff4baae93 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff2c54e6b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff2c55118 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff2c551cf in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff4baa51f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff4b5198b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff4b59c00 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00005555555de044 in main ()
(gdb) 
```

**Comment by kkartaltepe** [comment]
Please test using flatpak without third party plugins or on a modern system. If you can reproduce a trace on those we can consider reopening.

**Comment by ogmkp** [comment]
@kkartaltepe 
tested without media controls from @exeldro and no crash, I'm gonna open a issue to the project repo.
Thanks.

**Comment by ogmkp** [comment]
Hi @kkartaltepe 

I built OBS 29.0.2 on Debian 11 with QT6 following the official documentation and without any plugins, I deleted the ~/.config/obs-studio folder to get a clean run, I still have the problem, reproducible at all times, like 27.2.4 :+1: 

```
$ gdb obs
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from obs...
(No debugging symbols found in obs)
(gdb) r
Starting program: /usr/local/bin/obs 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea9ff700 (LWP 49753)]
[New Thread 0x7fffe95ff700 (LWP 49754)]
[New Thread 0x7fffe8dfe700 (LWP 49755)]
debug: Found portal inhibitor
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/local/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/locale.ini
debug: Attempted path: /usr/local/share/obs/obs-studio/locale.ini
debug: Attempted path: share/obs/obs-studio/locale/fr-FR.ini
debug: Attempted path: /usr/local/share/obs/obs-studio/locale/fr-FR.ini
info: Using preferred locale 'fr-FR'
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /usr/local/share/obs/obs-studio/themes/Yami.qss
info: Using EGL/X11
info: CPU Name: Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
info: CPU Speed: 3499.997MHz
info: Physical Cores: 2, Logical Cores: 4
info: Physical Memory: 15970MB Total, 1478MB Free
info: Kernel Version: Linux 6.0.0-0.deb11.6-amd64
info: Distribution: "Debian GNU/Linux" "11"
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.11
[New Thread 0x7fffdbfff700 (LWP 49758)]
[New Thread 0x7fffd37fe700 (LWP 49759)]
info: Qt Version: 6.4.2 (runtime), 6.4.2 (compiled)
info: Portable mode: false
[New Thread 0x7fffdb7fe700 (LWP 49760)]
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
info: OBS 29.0.2 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
	max buffering:   960 milliseconds
	buffering type:  dynamically increasing
[New Thread 0x7fffdaffd700 (LWP 49761)]
info: ---------------------------------
info: Initializing OpenGL...
[New Thread 0x7fffd8bff700 (LWP 49762)]
[New Thread 0x7fffd3fff700 (LWP 49763)]
[New Thread 0x7fffd19ff700 (LWP 49764)]
[New Thread 0x7fffd11fe700 (LWP 49765)]
[New Thread 0x7fffd09fd700 (LWP 49766)]
[New Thread 0x7fffbedff700 (LWP 49767)]
[New Thread 0x7fffbe5fe700 (LWP 49768)]
[New Thread 0x7fffbddfd700 (LWP 49769)]
[New Thread 0x7fffbd5fc700 (LWP 49770)]
[New Thread 0x7fffbcdfb700 (LWP 49771)]
[New Thread 0x7fff97fff700 (LWP 49772)]
info: Loading up OpenGL on adapter AMD AMD Radeon (TM) R9 380 Series (TONGA, DRM 3.48.0, 6.0.0-0.deb11.6-amd64, LLVM 11.0.1)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 20.3.5, shading language 4.60
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1280x720
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          Rec. 709/Partial
[New Thread 0x7fff973fe700 (LWP 49773)]
info: NV12 texture support not available
info: P010 texture support not available
[New Thread 0x7fff968ab700 (LWP 49774)]
info: Audio monitoring device:
	name: Par défaut
	id: default
info: ---------------------------------
[Detaching after fork from child process 49775]
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
[Detaching after fork from child process 49776]
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
[Detaching after fork from child process 49777]
libDeckLinkAPI.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
[Detaching after fork from child process 49778]
[New Thread 0x7fff960aa700 (LWP 49779)]
[Detaching after fork from child process 49780]
[Detaching after fork from child process 49781]
[Detaching after fork from child process 49782]
[Detaching after fork from child process 49783]
[Detaching after fork from child process 49784]
[Detaching after fork from child process 49785]
[Detaching after fork from child process 49786]
info: [pipewire] No captures available
[Detaching after fork from child process 49787]
[Detaching after fork from child process 49788]
[Detaching after vfork from child process 49789]
[Detaching after fork from child process 49791]
info: [obs-browser]: Version 2.19.0
info: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures_143.2591+g4204d54+chromium-103.0.5060.134 (compiled)
[Detaching after fork from child process 49792]
[New Thread 0x7fff6d9ff700 (LWP 49796)]
[New Thread 0x7fff6d1fe700 (LWP 49797)]
[New Thread 0x7fff5c9fd700 (LWP 49798)]
[New Thread 0x7fff535ff700 (LWP 49799)]
[New Thread 0x7fff52dfe700 (LWP 49800)]
[New Thread 0x7fff525fd700 (LWP 49801)]
[New Thread 0x7fff51dfc700 (LWP 49802)]
[New Thread 0x7fff515fb700 (LWP 49803)]
[New Thread 0x7fff50dfa700 (LWP 49804)]
[New Thread 0x7fff3bfff700 (LWP 49805)]
[New Thread 0x7fff3b7fe700 (LWP 49806)]
[New Thread 0x7fff3affd700 (LWP 49807)]
info: VAAPI: API version 1.10
[Thread 0x7fff3bfff700 (LWP 49805) exited]
[Thread 0x7fff50dfa700 (LWP 49804) exited]
[Thread 0x7fff515fb700 (LWP 49803) exited]
[Thread 0x7fff3b7fe700 (LWP 49806) exited]
[Thread 0x7fff51dfc700 (LWP 49802) exited]
[Thread 0x7fff52dfe700 (LWP 49800) exited]
[Thread 0x7fff525fd700 (LWP 49801) exited]
info: FFmpeg VAAPI H264 encoding supported
[Thread 0x7fff3affd700 (LWP 49807) exited]
[Thread 0x7fff535ff700 (LWP 49799) exited]
[Thread 0x7fff5c9fd700 (LWP 49798) exited]
[Thread 0x7fff6d1fe700 (LWP 49797) exited]
[Thread 0x7fff6d9ff700 (LWP 49796) exited]
[Detaching after fork from child process 49808]
[Detaching after fork from child process 49809]
[Detaching after fork from child process 49810]
[Detaching after fork from child process 49811]
[Detaching after fork from child process 49812]
info: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.1.0 | RPC Version: 1)
info: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.4.2 | Qt version (run-time): 6.4.2
info: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201
info: [obs-websocket] [Config::Load] (FirstLoad) Generating new server password.
info: [obs-websocket] [obs_module_load] Module loaded.
[Detaching after fork from child process 49813]
[Detaching after fork from child process 49814]
[New Thread 0x7fff5c9fd700 (LWP 49815)]
[Detaching after fork from child process 49816]
[New Thread 0x7fff6d1fe700 (LWP 49817)]
[Detaching after fork from child process 49818]
info: [vlc-video]: VLC 3.0.18 Vetinari found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-vst.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-pipewire.so
info:     linux-capture.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-output-ui.so
info:     decklink-captions.so
info: ---------------------------------
QLayout: Attempting to add QLayout "" to OBSBasic "OBSBasic", which already has a layout
QWidget::setTabOrder: 'first' and 'second' must be in the same window
info: ==== Startup complete ===============================================
info: No scene file found, creating default scene
[Thread 0x7fff6d1fe700 (LWP 49817) exited]
info: All scene data cleared
info: ------------------------------------------------
[New Thread 0x7fff6d1fe700 (LWP 49819)]
[Thread 0x7fff6d1fe700 (LWP 49819) exited]
[New Thread 0x7fff6d1fe700 (LWP 49820)]
[Thread 0x7fff6d1fe700 (LWP 49820) exited]
[New Thread 0x7fff6d1fe700 (LWP 49821)]
info: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.65) 15.0.0'
info: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_01_00.1.hdmi-stereo-extra3.monitor' (default)
info: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.65) 15.0.0'
info: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_input.pci-0000_00_1f.3.analog-stereo' (default)
info: Switched to scene 'Scène'
warning: Failed to glob scene collections
[New Thread 0x7fff6d9ff700 (LWP 49822)]
[New Thread 0x7fff51dfc700 (LWP 49823)]
[New Thread 0x7fff535ff700 (LWP 49824)]
[New Thread 0x7fff52dfe700 (LWP 49825)]
[Thread 0x7fff51dfc700 (LWP 49823) exited]
[Thread 0x7fff52dfe700 (LWP 49825) exited]
info: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Audio du Bureau)

warning: [rtmp-services plugin] Successfully updated file 'services.json' (version 220)
warning: [rtmp-services plugin] Successfully updated package (version 220)
[Thread 0x7fff5c9fd700 (LWP 49815) exited]
[Thread 0x7fff6d9ff700 (LWP 49822) exited]
[Thread 0x7fff535ff700 (LWP 49824) exited]
[New Thread 0x7fff6d9ff700 (LWP 49826)]
[New Thread 0x7fff52dfe700 (LWP 49827)]
[New Thread 0x7fff51dfc700 (LWP 49828)]
[Detaching after fork from child process 49829]
[Detaching after fork from child process 49830]
[New Thread 0x7fff525fd700 (LWP 49831)]
[New Thread 0x7fff2bfff700 (LWP 49832)]
[New Thread 0x7fff2b7fe700 (LWP 49833)]
[New Thread 0x7fff2affd700 (LWP 49834)]
[New Thread 0x7fff2a7fc700 (LWP 49835)]
[New Thread 0x7fff29ffb700 (LWP 49836)]
[New Thread 0x7fff297fa700 (LWP 49837)]
[New Thread 0x7fff28ff9700 (LWP 49838)]
[New Thread 0x7fff23fff700 (LWP 49839)]
[New Thread 0x7fff237fe700 (LWP 49840)]
[New Thread 0x7fff22ffd700 (LWP 49841)]
[New Thread 0x7fff227fc700 (LWP 49842)]
[New Thread 0x7fff21ffb700 (LWP 49843)]
[New Thread 0x7fff217fa700 (LWP 49844)]
[New Thread 0x7fff20ff9700 (LWP 49847)]
[Thread 0x7fff52dfe700 (LWP 49827) exited]
[Detaching after fork from child process 49853]
[New Thread 0x7fff52dfe700 (LWP 49854)]
[New Thread 0x7fff1bfff700 (LWP 49862)]
info: Switched to Preview/Program mode
info: ------------------------------------------------
info: [Media Source 'Source média']: settings:
	input:                   
	input_format:            (null)
	speed:                   100
	is_looping:              no
	is_linear_alpha:         no
	is_hw_decoding:          no
	is_clear_on_media_end:   yes
	restart_on_activate:     yes
	close_when_inactive:     no
	ffmpeg_options:          
info: User added source 'Source média' (ffmpeg_source) to scene 'Scène'
[New Thread 0x7fff1b7fe700 (LWP 49925)]
info: Set FFmpeg options: 
info: [Media Source 'Source média']: settings:
	input:                   udp://:5050
	input_format:            
	speed:                   100
	is_looping:              no
	is_linear_alpha:         no
	is_hw_decoding:          no
	is_clear_on_media_end:   yes
	restart_on_activate:     yes
	close_when_inactive:     no
	ffmpeg_options:          
[udp @ 0x7fff4c0513c0] attempted to set receive buffer to size 2097152 but it only ended up set as 425984
[New Thread 0x7fff1affd700 (LWP 49926)]
info: User Removed source 'Source média' (ffmpeg_source) from scene 'Scène'
--Type <RET> for more, q to quit, c to continue without paging--q
Quit
(gdb) bt
#0  0x00007ffff3e0ad2f in __GI___poll (fds=0x5555563b15e0, nfds=4, timeout=16) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff35230ae in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff35231cf in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4566599 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#4  0x00007ffff433022b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#5  0x00007ffff432c082 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#6  0x00005555555e49d4 in main ()
(gdb) 

```

Please, consider reopening this issue.

**Comment by kkartaltepe** [comment]
your gdb shows obs running normally, maybe you can try to describe what you mean by crash.

**Comment by ogmkp** [comment]
Ok thanks, I learn how this works actually, I haven't the good pratices.
I retested with the media-controls plugin and I do have a segfault with an obs crash that disappears entirely.
I have put gdb back on and I have the crash logged.
For this project and for the right project issue list, do I make a good backtrace now ? Thanks

```
info: User added source 'Source média' (ffmpeg_source) to scene 'Scène'
[New Thread 0x7fff6d9ff700 (LWP 69720)]
info: [Media Source 'Source média']: settings:
	input:                   udp://:5050
	input_format:            
	speed:                   100
	is_looping:              no
	is_linear_alpha:         no
	is_hw_decoding:          no
	is_clear_on_media_end:   yes
	restart_on_activate:     yes
	close_when_inactive:     no
	ffmpeg_options:          
info: Set FFmpeg options: 
[udp @ 0x7fff3c000c40] attempted to set receive buffer to size 2097152 but it only ended up set as 425984
[New Thread 0x7fff51dfc700 (LWP 69721)]
info: User Removed source 'Source média' (ffmpeg_source) from scene 'Scène'
--Type <RET> for more, q to quit, c to continue without paging--

Thread 44 "mp_media_thread" received signal SIG32, Real-time event 32.
[Switching to Thread 0x7fff51dfc700 (LWP 69721)]
0x00007ffff7e6c3da in __libc_recvfrom (fd=36, buf=0x7fff3c003050, len=65536, flags=0, addr=..., addrlen=0x7fff51dfb12c) at ../sysdeps/unix/sysv/linux/recvfrom.c:27
27	../sysdeps/unix/sysv/linux/recvfrom.c: Aucun fichier ou dossier de ce type.
(gdb) 
(gdb) c
Continuing.
warning: MP: Failed to open media: 'udp://:5050'
[Thread 0x7fff51dfc700 (LWP 69721) exited]

Thread 43 "mp_media_thread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff6d9ff700 (LWP 69720)]
0x0000555557630b00 in ?? ()
(gdb) c
Continuing.
[Thread 0x7fff6d9ff700 (LWP 69720) exited]
[Thread 0x7fff515fb700 (LWP 69697) exited]
[Thread 0x7fff52afd700 (LWP 69696) exited]
[Thread 0x7fff532fe700 (LWP 69695) exited]
[Thread 0x7fff6d1fe700 (LWP 69692) exited]
[Thread 0x7fff96158700 (LWP 69633) exited]
[Thread 0x7fff96959700 (LWP 69628) exited]
[Thread 0x7fff975fe700 (LWP 69627) exited]
[Thread 0x7fff97fff700 (LWP 69626) exited]
[Thread 0x7fffbcdfb700 (LWP 69625) exited]
[Thread 0x7fffbd5fc700 (LWP 69624) exited]
[Thread 0x7fffbddfd700 (LWP 69623) exited]
[Thread 0x7fffbe5fe700 (LWP 69622) exited]
[Thread 0x7fffbedff700 (LWP 69621) exited]
[Thread 0x7fffc89fb700 (LWP 69620) exited]
[Thread 0x7fffc91fc700 (LWP 69619) exited]
[Thread 0x7fffc99fd700 (LWP 69618) exited]
[Thread 0x7fffca1fe700 (LWP 69617) exited]
[Thread 0x7fffca9ff700 (LWP 69616) exited]
[Thread 0x7fffda7fc700 (LWP 69615) exited]
[Thread 0x7fffdb7fe700 (LWP 69613) exited]
[Thread 0x7fffdbfff700 (LWP 69612) exited]
[Thread 0x7fffe8dfe700 (LWP 69608) exited]
[Thread 0x7fffe95ff700 (LWP 69607) exited]
[Thread 0x7fffea9ff700 (LWP 69606) exited]
[Thread 0x7fffeb506440 (LWP 69602) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb) 
```

**Comment by ogmkp** [comment]
I have this now, is this still about obs-studio or exeldro's media-controls plugin?
What do you think about it?

```
Thread 43 "mp_media_thread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff6d9ff700 (LWP 72679)]
0x000055555770b240 in ?? ()
(gdb) bt
#0  0x000055555770b240 in  ()
#1  0x00007ffff4338323 in QMetaObject::invokeMethod(QObject*, char const*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) ()
    at /lib/x86_64-linux-gnu/libQt6Core.so.6
#2  0x00007fff8254c1f3 in QMetaObject::invokeMethod(QObject*, char const*, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)
    (val9=..., val8=..., val7=..., val6=..., val5=..., val4=..., val3=..., val2=..., val1=..., val0=..., member=0x7fff8254f6e2 "SetRestartState", obj=<optimized out>) at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs.h:287
#3  MediaControl::OBSMediaStopped(void*, calldata*) (data=<optimized out>, calldata=<optimized out>)
    at /home/runner/work/obs-media-controls/obs-media-controls/UI/frontend-plugins/media-controls/media-control.cpp:158
#4  0x00007ffff678a4fb in signal_handler_signal () at /usr/local/lib/libobs.so.0
#5  0x00007ffff6781572 in obs_source_media_ended () at /usr/local/lib/libobs.so.0
#6  0x00007fff9536fc1d in  () at /usr/local//lib/obs-plugins/obs-ffmpeg.so
#7  0x00007ffff7e61ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff3e16a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

**Comment by kkartaltepe** [comment]
report this to the plugin author.
