### ISSUE TITLE
OBS Crash When Open Settings

### ISSUE THREAD

**Issue by AntonioBerna** [obsproject/obs-studio#8986]
### Operating System Info

Other

### Other OS

Manjaro Linux

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/aD4frZNvZz8hf26O

### Expected Behavior

I expected the obs studio settings to open

### Current Behavior

The obs studio program has closed. I also tried to run it from the terminal and when I tried to open the settings on the terminal I got the message "Segmentation Fault"

### Steps to Reproduce

1.Open OBS Studio
2.Open Settings
3.
...

**Comment by kkartaltepe** [comment]
Please provide a backtrace from gdb.

**Comment by AntonioBerna** [comment]
> Please provide a backtrace from gdb.

Could you tell me the steps please?

**Comment by AntonioBerna** [comment]
> Please provide a backtrace from gdb.

If I try start obs with ```gdb obs``` and when i click on settings this is the report of gdb:

```
Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
XDisplayString (dpy=0x0) at /usr/src/debug/libx11/libX11-1.8.4/src/Macros.c:119
Downloading source file /usr/src/debug/libx11/libX11-1.8.4/src/Macros.c
119     char *XDisplayString(Display *dpy) { return (DisplayString(dpy)); } 
```

**Comment by kkartaltepe** [comment]
you need to enter `bt` in the prompt to create the backtrace after you see the output you posted.

**Comment by tytan652** [comment]
Duplicate of #8056

**Comment by AntonioBerna** [comment]
> you need to enter `bt` in the prompt to create the backtrace after you see the output you posted.

```
(gdb) bt
#0  XDisplayString (dpy=0x0)
    at /usr/src/debug/libx11/libX11-1.8.4/src/Macros.c:119
#1  0x00007fff567a4a1d in __vaDriverInit_1_13 ()
    at /usr/lib/dri/nvidia_drv_video.so
#2  0x00007ffff32489c3 in  () at /usr/lib/libva.so.2
#3  0x00007ffff324bce0 in vaInitialize () at /usr/lib/libva.so.2
#4  0x00007fff77c74b56 in vaapi_open_device ()
    at /usr//lib/obs-plugins/obs-ffmpeg.so
#5  0x00007fff77c75104 in vaapi_device_h264_supported ()
    at /usr//lib/obs-plugins/obs-ffmpeg.so
#6  0x00007fff77c78317 in  () at /usr//lib/obs-plugins/obs-ffmpeg.so
#7  0x00007ffff6546b5f in obs_get_encoder_properties () at /usr/lib/libobs.so.0
#8  0x00005555556316ce in  ()
#9  0x00007ffff476e013 in QObject::event(QEvent*) ()
    at /usr/lib/libQt6Core.so.6
#10 0x00007ffff5850c36 in QFrame::event(QEvent*) ()
    at /usr/lib/libQt6Widgets.so.6
#11 0x00007ffff577167b in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /usr/lib/libQt6Widgets.so.6
#12 0x00007ffff472b718 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /usr/lib/libQt6Core.so.6
#13 0x00007ffff472b906 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt6Core.so.6
--Type <RET> for more, q to quit, c to continue without paging--
#14 0x00007ffff4927804 in  () at /usr/lib/libQt6Core.so.6
#15 0x00007ffff3ec753b in g_main_context_dispatch ()
    at /usr/lib/libglib-2.0.so.0
#16 0x00007ffff3f24219 in  () at /usr/lib/libglib-2.0.so.0
#17 0x00007ffff3ec61a2 in g_main_context_iteration ()
    at /usr/lib/libglib-2.0.so.0
#18 0x00007ffff4925754 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#19 0x00007ffff4735360 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#20 0x00007ffff59bfa73 in QDialog::exec() () at /usr/lib/libQt6Widgets.so.6
#21 0x00005555556940ce in  ()
#22 0x00005555555f2bf7 in  ()
#23 0x00007ffff478269c in  () at /usr/lib/libQt6Core.so.6
#24 0x00007ffff588493a in  () at /usr/lib/libQt6Widgets.so.6
#25 0x00007ffff5884f48 in  () at /usr/lib/libQt6Widgets.so.6
#26 0x00007ffff58850a5 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
    at /usr/lib/libQt6Widgets.so.6
#27 0x00007ffff57c296d in QWidget::event(QEvent*) ()
    at /usr/lib/libQt6Widgets.so.6
#28 0x00007ffff577167b in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /usr/lib/libQt6Widgets.so.6
#29 0x00007ffff5774053 in QApplication::notify(QObject*, QEvent*) ()
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/lib/libQt6Widgets.so.6
#30 0x00007ffff472b718 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /usr/lib/libQt6Core.so.6
#31 0x00007ffff576f577 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
    at /usr/lib/libQt6Widgets.so.6
#32 0x00007ffff57d737b in  () at /usr/lib/libQt6Widgets.so.6
#33 0x00007ffff57d28fd in  () at /usr/lib/libQt6Widgets.so.6
#34 0x00007ffff577167b in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /usr/lib/libQt6Widgets.so.6
#35 0x00007ffff472b718 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /usr/lib/libQt6Core.so.6
#36 0x00007ffff4da858c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt6Gui.so.6
#37 0x00007ffff4e103fc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Gui.so.6
#38 0x00007fffe338db2f in  ()
    at /usr/lib/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6
#39 0x00007ffff3ec753b in g_main_context_dispatch ()
    at /usr/lib/libglib-2.0.so.0
#40 0x00007ffff3f24219 in  () at /usr/lib/libglib-2.0.so.0
#41 0x00007ffff3ec61a2 in g_main_context_iteration ()
    at /usr/lib/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#42 0x00007ffff4925754 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#43 0x00007ffff4735360 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#44 0x00007ffff472eb9a in QCoreApplication::exec() ()
    at /usr/lib/libQt6Core.so.6
#45 0x00005555555dfdf0 in main ()
(gdb) 
```

**Comment by tytan652** [comment]
The crash was not in startup because the first DRI device that support H264 encode was using another driver but while opening settings
 Each DRI device is checked and so the VDPAU VAAPI driver is loaded and cause the crash.

**Comment by AntonioBerna** [comment]
> The crash was not in startup because the first DRI device that support H264 encode was using another driver. But while opening settings, each DRI device is checked and so the VDPAU VAAPI driver is loaded and cause the crash.

how can I solve?

**Comment by tytan652** [comment]
Read the issue that I linked.

https://github.com/obsproject/obs-studio/issues/8056#issuecomment-1380799761

**Comment by AntonioBerna** [comment]
> Read the issue that I linked earlier.
> 
> [#8056 (comment)](https://github.com/obsproject/obs-studio/issues/8056#issuecomment-1380799761)

Thanks a lot, I managed to fix it! But now I can no longer select the video card in the ```Output > Encoder``` section, where I only have ```x264``` and ```ffmpeg```
