### ISSUE TITLE
OBS crashing when trying to open Settings Dialog

### ISSUE THREAD

**Issue by FFS2309** [obsproject/obs-studio#9993]
### Operating System Info

Other

### Other OS

RedHat Enterprise Linux Server 9.3

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/CosoFaOSth2tz0PX

### OBS Studio Crash Log URL

https://obsproject.com/logs/CosoFaOSth2tz0PX

### Expected Behavior

I expect the Settings dialog to open.

### Current Behavior

OBS-Studio crashes.

### Steps to Reproduce

1. Open OBS-Studio
2. Try to open settings through either context menu or settings button in controls dock

### Anything else we should know?

I see the following backtrace after the crashes:

```
#0  0x00007ffff3ea154c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff3e54d06 in raise () from /lib64/libc.so.6
#2  0x00007ffff3e287f3 in abort () from /lib64/libc.so.6
#3  0x00007ffff42a1a01 in __gnu_cxx::__verbose_terminate_handler() [clone .cold] () from /lib64/libstdc++.so.6
#4  0x00007ffff42ad37c in __cxxabiv1::__terminate(void (*)()) () from /lib64/libstdc++.so.6
#5  0x00007ffff42ad3e7 in std::terminate() () from /lib64/libstdc++.so.6
#6  0x00007ffff42ad649 in __cxa_throw () from /lib64/libstdc++.so.6
#7  0x00007ffff42a42b3 in std::__throw_logic_error(char const*) () from /lib64/libstdc++.so.6
#8  0x00005555557c6dc5 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) [clone .constprop.0] ()
#9  0x000055555573a9b7 in OBSBasicSettings::SimpleRecordingEncoderChanged() ()
#10 0x00007ffff47cdee4 in void doActivate<false>(QObject*, int, void**) () from /lib64/libQt6Core.so.6
#11 0x00007ffff5dc50a2 in QSpinBox::valueChanged(int) () from /lib64/libQt6Widgets.so.6
#12 0x00007ffff5dc1a79 in QAbstractSpinBoxPrivate::setValue(QVariant const&, EmitPolicy, bool) () from /lib64/libQt6Widgets.so.6
#13 0x00007ffff5dc5a1c in QSpinBox::setValue(int) () from /lib64/libQt6Widgets.so.6
#14 0x000055555572172a in OBSBasicSettings::LoadSimpleOutputSettings() ()
#15 0x000055555572b9c7 in OBSBasicSettings::LoadSettings(bool) ()
#16 0x00005555556a00d2 in OBSBasic::on_action_Settings_triggered() ()
#17 0x000055555560c821 in OBSBasic::qt_metacall(QMetaObject::Call, int, void**) ()
#18 0x00007ffff47ce1d1 in void doActivate<false>(QObject*, int, void**) () from /lib64/libQt6Core.so.6
#19 0x00007ffff5ceb8d6 in QAbstractButton::clicked(bool) () from /lib64/libQt6Widgets.so.6
#20 0x00007ffff5cebb6e in QAbstractButtonPrivate::emitClicked() () from /lib64/libQt6Widgets.so.6
#21 0x00007ffff5ced204 in QAbstractButtonPrivate::click() () from /lib64/libQt6Widgets.so.6
#22 0x00007ffff5ced433 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /lib64/libQt6Widgets.so.6
#23 0x00007ffff5c1ae58 in QWidget::event(QEvent*) () from /lib64/libQt6Widgets.so.6
#24 0x00007ffff5bc17b6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib64/libQt6Widgets.so.6
#25 0x00007ffff5bcb260 in QApplication::notify(QObject*, QEvent*) () from /lib64/libQt6Widgets.so.6
#26 0x00007ffff476dbe8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib64/libQt6Core.so.6
#27 0x00007ffff5bc9d07 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /lib64/libQt6Widgets.so.6
#28 0x00007ffff5c2d3fb in QWidgetWindow::handleMouseEvent(QMouseEvent*) () from /lib64/libQt6Widgets.so.6
#29 0x00007ffff5c301e8 in QWidgetWindow::event(QEvent*) () from /lib64/libQt6Widgets.so.6
#30 0x00007ffff5bc17b6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib64/libQt6Widgets.so.6
#31 0x00007ffff476dbe8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib64/libQt6Core.so.6
#32 0x00007ffff50096a0 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /lib64/libQt6Gui.so.6
#33 0x00007ffff50629fc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt6Gui.so.6
#34 0x00007fffecdf97ae in xcbSourceDispatch(_GSource*, int (*)(void*), void*) () from /lib64/libQt6XcbQpa.so.6
#35 0x00007ffff3d19e2f in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#36 0x00007ffff3d6f108 in g_main_context_iterate.constprop () from /lib64/libglib-2.0.so.0
#37 0x00007ffff3d175f3 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#38 0x00007ffff49fcd5e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt6Core.so.6
#39 0x00007ffff477a193 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt6Core.so.6
#40 0x00007ffff4776206 in QCoreApplication::exec() () from /lib64/libQt6Core.so.6
#41 0x00005555555f4da1 in main ()
```

**Comment by tytan652** [comment]
Please report firstly to RHEL bug tracker.

And once it has been proved that the cause is not due to applied patches by packagers, you can ask for this issue to be re-opened.
